### ISSUE TITLE
Add tagging command to Hamster CLI (maybe GUI)

### ISSUE THREAD

**Issue by sobutz** [projecthamster/hamster#104]
It would be nice to set the tags of multiple entries at once:

```
hamster tag pancakes 2012-08-01 2012-08-30 #tag1 #tag2 #tag3
```

This way it would be possible to tag a set of entries as "invoiced" for example.

**Comment by ederag** [comment]
https://github.com/projecthamster/hamster/issues/19 would solve this as well ?
