### ISSUE TITLE
Text hook to continue previous task

### ISSUE THREAD

**Issue by tstriker** [projecthamster/hamster#11]
original https://bugzilla.gnome.org/show_bug.cgi?id=639473

**Comment by ederag** [comment]
There is no text hook yet,
but with PR #387 and #415, the workflow described in the original report is now handled gracefully:
select the activity to clone (by mouse or keyboard arrows),
hit `Ctrl-+` or `Ctrl-r` ("run" or "resume")
just type in the time, e.g. `-10` (thanks to the preselection, typing replaces the current time information)
hit `enter`
Done

**Comment by ederag** [comment]
Done. This should solve the original issue. Closing.
Please file a new issue if you wish the same from the command-line,
with an example of the preferred syntax.
