### ISSUE TITLE
Weird HTML Report Output

### ISSUE THREAD

**Issue by thiagof** [projecthamster/hamster#110]
The reporter tool is making any wrong expression calculation with the times.

The attached result shows how my report actualy was output in a given month.

Issues on: total time, 1st category, tags (other months with tag name problem too)

![screenshot from 2013-07-18 17 39 56](https://f.cloud.github.com/assets/211201/822200/45bb5630-efea-11e2-8787-e27bb35ba684.png)

Built from master in fedora 19.

**Comment by toupeira** [comment]
Closing this, feel free to reopen if you still experience this issue with current master.
