### ISSUE TITLE
Appdata file for hamster-time-tracker

### ISSUE THREAD

**Issue by sanjayankur31** [projecthamster/hamster#122]
Hi,

I've written up an appdata file for hamster-time-tracker so it can be part of gnome-software in a more complete manner. I've placed it here:  
http://ankursinha.fedorapeople.org/hamster-time-tracker/hamster-time-tracker.appdata.xml

I thought I'd open a pull request, but I'm not well versed enough with waf to make changes to the build system yet. 

It'll be great if this file can be included in future releases, and optionally, if the build system could install it to /usr/share/appdata. The installation isn't necessary, since us maintainers can do it manually too.

Please feel free to edit the file to improve the descriptions, add more screenshots etc. The screenshots must be 16:9 in aspect ratio though. Here's a post explaining how to make such screenshots:
http://blogs.gnome.org/hughsie/2013/10/08/how-to-take-169-screenshots/

More information on appdata files:
http://people.freedesktop.org/~hughsient/appdata/

I've submitted hamster-time-tracker for review to Fedora and have included this appdata file manually for the time being. 

https://bugzilla.redhat.com/show_bug.cgi?id=1036254

Thanks,
Ankur

**Comment by toupeira** [comment]
@sanjayankur31 closing this old issue, but let me know if you're still interested in Fedora packaging!

**Comment by sanjayankur31** [comment]
Sure. I'm maintaining it in Fedora already and will continue to do so as newer versions are released.
