### ISSUE TITLE
Retrieve time data with SQLite

### ISSUE THREAD

**Issue by dhuyvetter** [projecthamster/hamster#151]
I cannot open hamster any more, see issue: https://github.com/projecthamster/hamster/issues/150 I used it to keep track of time spend on my last freelance project and would like to somehow retrieve the data, since otherwise I cannot make an invoice. Is there a way to retrieve the data via sqlite? I tried copying the database from ~/.local/share/hamster-applet/hamster.db and opening it with SQLite Database Browser: http://sqlitebrowser.sourceforge.net/ but I can only find the tags/categories and no actual time data. This is quite important to me as I was only keeping track of my billable hours via hamster and have no other backup.

**Comment by GeraldJansen** [comment]
The hint Backup help page suggests using [sqlitebrowser](https://sqlitebrowser.org/) on ~/.local/share/hamster-applet/hamster.db. In addition the hamster[-cli] --help indicates the various export options (tsv etc.). Perhaps that is adequate to close this issue.
