### ISSUE TITLE
Unable to 'stop tracking' if an activity takes longer then 24 hours

### ISSUE THREAD

**Issue by bmarien** [projecthamster/hamster#152]
Basically, if you forget to stop tracking when you leave the office, in the morning 'stop tracking' does not work any longer. In this case you need to 'add previous activity' and unselect the 'in progress'  flag.

**Comment by ederag** [comment]
Should be fixed by PR #376.
For testing, please consider PR #372 that has been rebased on it, 
and features some other improvements in the UI.
Feedback welcome !
