### ISSUE TITLE
Autocomplete introduces space in project text and tags

### ISSUE THREAD

**Issue by npassaro** [projecthamster/hamster#154]
If I introduce this as a time report

```
11:00 12:00 BPC-261 - Task title@Project#code
```

When I try to introduce a new one using auto-complete it will look like:

```
11:00 12:00 BPC-261 - Task title@Project<space_here>#code,
```

Which is accounted as a new project.

This may be two different bugs. Addition of space in the view and not stripping the space when accounting for the time in a given category. :P

Cheers!

**Comment by ederag** [comment]
Thanks for the report.

Seems fixed now.
Tried to enter
```BPC-261 - Task title@Project#code```
and the autocompletion indeed became
```BPC-261 - Task title@Project #code```
which is a feature (one space between category and tags makes it clearer to read),
but now the spaces are stripped upon reading, 
hence the autocompleted form is considered as equal to the input one.
