### ISSUE TITLE
Super + H on Ubuntu

### ISSUE THREAD

**Issue by TimBozeman** [projecthamster/hamster#156]
Awesome app!

I installed hamster with the Ubuntu Software Center. Can I still use the command 

./autogen.sh --prefix=/usr/ --with-gconf-schema-file-dir=/usr/share/gconf/schemas/

from http://projecthamster.wordpress.com/2008/03/30/hamster-at-your-fingertips/ ? Says no file found.

**Comment by marcbria** [comment]
Sorry but I'm trying to deal with the same issue for linux Mint 17.
I love hamster but without key binding the workflow is extremely slow.
Any suggestion about how to fix it on Mint + cinnamon?

**Comment by toupeira** [comment]
@marcbria are you using Hamster standalone, or the [Cinnamon applet](https://github.com/projecthamster/cinnamon-applet)? If the latter, please re-submit this issue under that repository.

**Comment by marcbria** [comment]
You are right. Sorry for the annoyance.
