### ISSUE TITLE
Browse to activity name

### ISSUE THREAD

**Issue by TomRoche** [projecthamster/hamster#159]
**summary:** older hamster versions had functionality to browse to activity by name. Can this be done in newer hamster, e.g., [release=1.04](https://github.com/projecthamster/hamster/releases/tag/hamster-time-tracker-1.04)? If not, consider this to be a feature request.

**details:**

I previously had hamster (Help>About>version=2.91.3) installed on an older [LMDE](https://en.wikipedia.org/wiki/Linux_Mint#Linux_Mint_Debian_Edition)/MATE box. Now I also have a newer LMDE/Cinnamon box, on which I installed hamster and transferred the old data with the following procedure:

1) installed dependencies

```
sudo aptitude update
sudo aptitude install git-core gettext intltool python-gconf python-xdg
```

2) installed hamster release=1.04

```
URI='https://github.com/projecthamster/hamster/archive/hamster-time-tracker-1.04.tar.gz'
UNPACK_DIR_ROOT='/tmp'
UNPACK_DIR_NAME='hamster-hamster-time-tracker-1.04' # empirically
HAMSTER_DATA_DIR_FROM_HOME='.local/share/hamster-applet'
HAMSTER_DATA_PATH="${HOME}/${HAMSTER_DATA_DIR_FROM_HOME}/hamster.db"

UNPACK_DIR="${UNPACK_DIR_ROOT}/${UNPACK_DIR_NAME}"
pushd ${UNPACK_DIR_ROOT}/
wget -O - ${URI} | tar xfz -
lsalh ${UNPACK_DIR}/
popd
pushd ${UNPACK_DIR}/
./waf configure build --prefix=/usr
sudo ./waf install
# backup fresh DB
mv ${HAMSTER_DATA_PATH} ${HAMSTER_DATA_PATH}.0
chmod a-w ${HAMSTER_DATA_PATH}.0
```

3) added hamster applet to Cinnamon panel per [these instructions](http://cinnamon-spices.linuxmint.com/applets/view/140)

4) copied hamster data from old box to new, like `rsync -avh --append oldbox:${HAMSTER_DATA_DIR_FROM_HOME}/ newbox:${HAMSTER_DATA_DIR_FROM_HOME}/`

5) restart hamster (to pickup new data): `killall hamster-service && killall hamster-windows-service`

The good news is, hamster is seeing my data when I do `Show Overview`. The bad news is:

On the old hamster, I could choose to restart a previous activity by name by clicking in the Activity textbox, which dropped down a list of previous activity names, with name of most recent activity at top of list. On the new hamster, I'm not seeing a similar way to browse and choose from previous activities. Am I missing something? If not, please add this as a feature request.

**Comment by ederag** [comment]
There is a filter (search) in the overview,
and there is an auto-complete feature in the add activity dialog.
(tested with [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1))
Is it enough ?
