### ISSUE TITLE
Portions of UI unreadable when using gnome global dark theme

### ISSUE THREAD

**Issue by bendavis78** [projecthamster/hamster#164]
Global Dark Theme is a setting in Gnome3:
![image](https://cloud.githubusercontent.com/assets/324392/3273158/1c9446b4-f321-11e3-92ae-5fba7be0fe25.png)

The left-bar on the main view doesn't fit the theme, and while the foreground text is the correct color, the background is still light, making it near impossible to read.
![image](https://cloud.githubusercontent.com/assets/324392/3273150/f8ae0802-f320-11e3-88f1-621c58f6cae1.png)

**Comment by ubugnu** [comment]
Hi, this is a very annoying bug, especially when you find that calling hamster with the default (non dark) theme does nothing! env GTK_THEME=Adwaita hamster

**Comment by ederag** [comment]
Thanks for the clear report.
Should be fixed by PR #391. Please test and give feedback there !
