### ISSUE TITLE
TSV export fails for more large number of entries

### ISSUE THREAD

**Issue by npassaro** [projecthamster/hamster#172]
Hi,

Not sure how many entries are needed to verify this bug. But, if you try to export a month worth of logs with at least 25 entries per week the TSV export will not show all the entries.

Cheers

**Comment by ederag** [comment]
Looks like it has been fixed. Tested in [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1) with more than 2000 entries.
