### ISSUE TITLE
Make Unity indicator official

### ISSUE THREAD

**Issue by holocronweaver** [projecthamster/hamster#184]
A status icon makes hamster much easier to keep track of.

Currently the only hamster status icon that works in the Unity desktop environment is the hamster indicator (http://www.webupd8.org/2011/07/install-hamster-indicator-time-tracking.html).  From what I can tell, it has been abandoned by its creator.  Since it is no longer updated for the latest hamster release, Ubuntu is shipping an old version of hamster in its repositories so that the indicator continues to function.

I feel a status icon is critical enough to hamster functionality, and Ubuntu a popular enough distro, that it should be officially supported, either as a separate git repo under projecthamster or within the hamster repo.  Doing so would allow Ubuntu to package newer hamster versions (a good thing for both devs and users).  Plus it would make it easier for others to improve Unity integration by making contributions.

We could also use this opportunity to fix #156 and finally get Ubuntu support into proper shape.  As-is, the git version of Hamster is not very usable on Ubuntu out of the box.

I am willing to do the bulk of the work to make this happen, but want to hear thoughts from the maintainers and community before I proceed.

(BTW, pull request #82 seems to have already integrated the indicator into hamster.  May be worth a look.)

**Comment by einmalfel** [comment]
Is unity-indicator project abandoned? I've posted pull-request more than a month ago but still no response. Does it have any maintainer?

**Comment by nchachereau** [comment]
Hi Vasily,

sorry, I've been extremely busy... I'll look into your PR this week-end.

It is great having someone else contributing to the code!

**Comment by daytonb** [comment]
Any chance this work will also result in a system tray entry for KDE Plasma 5's system tray?

**Comment by holocronweaver** [comment]
Unless KDE has a Unity indicator interface, I don't see how it could.

**Comment by ederag** [comment]
Further discussions about unity can go to
https://github.com/projecthamster/unity-indicator/issues
And for the rewrite hamster-gtk/unity issues:
https://github.com/projecthamster/hamster-gtk/issues?utf8=%E2%9C%93&q=unity
