### ISSUE TITLE
Summary row issues

### ISSUE THREAD

**Issue by jamesfryer** [projecthamster/hamster#187]
I recently upgraded Ubuntu to 14.04 and got a Hamster upgrade thrown in for free. I dislike the new summary row (showing the totals for the categories, and the Add Earlier and Overview buttons) for two reasons:
1. having it there at all uses up vertical space which is in short supply
2. The summary extends the window making it wider and wider

Could it be made optional so I can turn it off?

A summary of the number of hours worked in a day would be useful, but this could be at the top of the window where there is plenty of space.

**Comment by ederag** [comment]
Closing as outdated. The interface has changed a lot.
