### ISSUE TITLE
Allowing different Templates for exports

### ISSUE THREAD

**Issue by Csardelacal** [projecthamster/hamster#193]
Hello!

I use Hamster to track my time as a freelance and there is one thing that would save me a ton of time. While some clients like the HTML report that it generates because it's clean and simple and gives them a good overview some of them actually prefer to have a CSV export with 'raw' data.

Would it be possible to allow selecting a template rather than having to replace your report file of choice every time I export the data?

**Comment by Profpatsch** [comment]
I recommend changing the html it generates to semantic html5 instead of table-based with css & js built-in.

**Comment by jessecfisher** [comment]
You can export to a TSV file. I think this file should be compatible with all spreadsheet software and function just as one would expect a CSV file to function.

#### GUI

1. Starting from the main `hamster` window.
2. Tracking -> Overview
3. Overview
4. Save report...
5. Dropdown select "Tab-Separated Values (TSV)"
    Note: The default option is "HTML Report"
6. Type a filename ending with a `.tsv` extension

#### Command Line example

    $ hamster export tsv 2015-04-01 2015-04-25

**Comment by ederag** [comment]
Thanks to PR #393, the help pages are visible now.
The TSV export is described in
https://github.com/projecthamster/hamster/blob/b34a2f780da16c66e627ade3e39f9cea0a02e3e1/help/C/reports.page#L11-L14
