### ISSUE TITLE
Adding an activity after midnight registers it to wrong date

### ISSUE THREAD

**Issue by nchachereau** [projecthamster/hamster#196]
### Steps to reproduce (with current trunk)
- in the overview window, click on the [+] icon (or run `hamster add`) to open the “add activity” window
- add an activity starting at e.g. 00:02 and ending at e.g. 00:24, without touching the date widget (i.e. adding it to the current day)
### Expected result

The activity gets added to the date shown in the preview widget (e. g. in this case, 9 November 2014, 00:02 to 00:24), even though it'll be shown with the activities of 8 November in the overview

![Add activity window](https://cloud.githubusercontent.com/assets/904912/5059220/09e18a56-6d13-11e4-9604-3fffeb060a04.png)
### Actual result

The activity gets added to 8 November 2014 (and shown in the overview with the activities of 7 November)

![Overview window](https://cloud.githubusercontent.com/assets/904912/5059235/dd08752a-6d13-11e4-954d-e0d0382123c9.png)

(For added fun, try registering an activity starting before midnight and ending after it. It will result in a negative duration :laughing: )

**Comment by koem** [comment]
this has to do with the setting "new day starts at". Everything before that time of day is shown on the day before.

But for the negative time recording you should file another bug.

**Comment by nchachereau** [comment]
> this has to do with the setting "new day starts at". Everything before that time of day is shown on the day before.

Please try reproducing my bug. This is an actual bug, not a misunderstanding of the interface. The activity should be shown on the day before, that is true, but not two days before! (In the case I describe above: I add "Arrosage des plantes" on November 9, 00:02 to 00:24, expecting it to show up on the end of the November 8 day. It ends up on November 7.)

**Comment by ederag** [comment]
Thanks for the report.
This has been fixed in [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
