### ISSUE TITLE
Save button in New activity window is grayed out

### ISSUE THREAD

**Issue by nchachereau** [projecthamster/hamster#198]
When you open the window to start a new activity, and start typing (let's say “Picking up groceries@Errands”), the “Save” button remains grayed out unless you specifically add the start time (“17:01 Picking up...“)

Is this the expected behavior? As a user, I would expect being able to add an activity starting now without stating the time. Especially as: this was Hamster's old behavior and it's actually possible to add an activity this way in spite of the gray button (just press Enter).

**Comment by helmo** [comment]
A fair bit annoying ... one work around I discovered was to use the autocomplete feature(Arrow key down, or click on the down facing arrow on the right)

**Comment by ederag** [comment]
Should be fixed by bba1a5b.
Thanks for the report !
