### ISSUE TITLE
Cannot edit tags under 'Categories and Tags'

### ISSUE THREAD

**Issue by d4nyll** [projecthamster/hamster#206]
The `Tags that should appear in autocomplete` section under the `Categories and Tags` tab in the `Preferences` window has virtually disappeared. I cannot resize it. Using Ubuntu 14.04 64-bit. Application at its latest version.

![bug](https://cloud.githubusercontent.com/assets/9997953/5405811/2a14647e-81e5-11e4-8404-dd3f7168046f.png)

**Comment by rolfkleef** [comment]
Same here. I'm using Adwaita, the default theme on Gnome (on Ubuntu 14.10), where it only shows a very small line on the right. When I switch to Ambiance, High Contrast or Radiance, it looks like the screenshot above: a line across the width of the window.

![20150206-selection-002](https://cloud.githubusercontent.com/assets/223935/6078883/7d2220d0-adfe-11e4-9ecb-485e3a79c0c6.png)

**Comment by maocheia** [comment]
same in portuguese, ubuntu 14.04 (64bit) with the default theme ambiance.
the hamster-indicator package version is 0.1+037dd2e-0ubuntu2
![captura de ecra de 2015-03-24 20 03 33](https://cloud.githubusercontent.com/assets/2250475/6811601/e6286536-d260-11e4-9cea-27689d919792.png)

**Comment by brimlar** [comment]
I don't know if this is the proper fix, but opening /usr/share/hamster-applet/preferences.ui and changing line 607 from:

`<property name="expand">False</property>`

to:

`<property name="expand">True</property>`

got that text field to show up properly.

**Comment by rolfkleef** [comment]
brilliant, thanks :-) I made a pull request for it.

**Comment by toupeira** [comment]
Fixed by #237
