### ISSUE TITLE
workspace switching does not seem to work

### ISSUE THREAD

**Issue by mbojan** [projecthamster/hamster#209]
I'm runing ubuntu with xfce. I installed release 1.04 as instructed in `README`. I launch hamster from the console. Switching workspaces (no compiz) does not seem change the tracked activity. The console shows the following output

```
/usr/local/lib/python2.7/dist-packages/hamster/today.py:119: GtkWarning: _gtk_accel_group_attach: assertion 'g_slist_find (accel_group->acceleratables, object) == NULL' failed
  self.window.add_accel_group(self.accel_group)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/hamster/today.py", line 341, in on_menu_about_activate
    dialogs.about.show(self.window)
  File "/usr/local/lib/python2.7/dist-packages/hamster/configuration.py", line 111, in show
    self.dialog_close_handlers[dialog] = dialog.connect("on-close", self.on_close_window)
AttributeError: 'About' object has no attribute 'connect'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/hamster/today.py", line 398, in on_workspace_changed
    activity = dict(name = activity.name,
AttributeError: 'dbus.Dictionary' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/hamster/today.py", line 398, in on_workspace_changed
    activity = dict(name = activity.name,
AttributeError: 'dbus.Dictionary' object has no attribute 'name'
```
the last two seem relevant. Is there any way to fix it or further debug it. I love hamster and my work depends on it. Thanks!

**Comment by freddy-k** [comment]
sorry to disturb but I'am still experiencing the same problems here. 
I'm running hamster-time-tracker 1.04-2 on Arch Linux and getting the exact same error message as mbojan. Any Idea what I could try to make things work on my side?

Greets freddy

**Comment by aurelien-naldi** [comment]
I would like to use it as well and it also fails to work for me (in Fedora 22). It looks like it was completely removed from master, so I started implementing it again (just the backend code using wnck, no GUI). Can I propose a patch for it (and for resuming paused activity on screen unlock)?

**Comment by toupeira** [comment]
@aurelien-naldi yes that would be very welcome, feel free to submit a PR!

I'll close this issue though since it does look like workspace tracking was removed at some point, though the setting is still there in the GConf schema.
