### ISSUE TITLE
hamster doesn't start after moving db-file

### ISSUE THREAD

**Issue by daanmarselis** [projecthamster/hamster#211]
Hi,

I used to back-up the hamster database in dropbox via a symlink. Since I moved the file in dropbox, Hamster doesn't start. I tried putting the original db-file back in dropbox, without result. I also tried reinstalling the software, but it still doesn't work. I use ubuntu 14.04.

How can I fix this?
And how can I get the data from the old db-file? I would hate to lose the data...

Thanks!
Daan

**Comment by toupeira** [comment]
The database is located in `~/.local/share/hamster-applet/hamster.db`. I'm not sure how SQLite deals with symlinks, you might have more luck with symlinking *from* your Dropbox *to* this path instead of the other way around.

**Comment by losvald** [comment]
I have been using symlinks to Sqlite3 databases for quite a while from various applications (including simple Python scripts). If hamster does not work with those, I would call it a bug on the hamster's side.

After all symbolic links are resolved by the OS / system calls. It seems like hamster is trying to be smart and avoid standard practice when opening files. Please reopen and fix!

**Comment by ederag** [comment]
Symlinks (aka symbolic links, or soft links) *targets* are *not* monitored.
This is a [known issue](https://gitlab.gnome.org/GNOME/glib/issues/144) of `glib`.
The [workaround](https://github.com/projecthamster/hamster/issues/211#issuecomment-146682261) mentioned by @toupeira is valid: create a symlink in the other directory pointing to
`~/.local/share/hamster-applet/hamster.db` instead.
If that is not possible (for instance if the symlink is replaced by a regular file upon synchronization),
please ask here for reopening.
