### ISSUE TITLE
Install with python3 fails

### ISSUE THREAD

**Issue by auipga** [projecthamster/hamster#214]
As you can see [here](http://stackoverflow.com/a/7520724/816362) your install script is not compatible with python3 anymore.
put `#!/usr/bin/env python2` in each file and it will work. I don't know whether this breaks install for others, so I won't create a PR.

here is my solution:

`cd` in your cloned repo, then run:
```sh
find ./ -type f -exec sed -i -e 's/#!\/usr\/bin\/env python/#!\/usr\/bin\/env python2/g' {} \;
find ./ -type f -exec sed -i -e 's/#! \/usr\/bin\/env python/#!\/usr\/bin\/env python2/g' {} \;
```
(the first command will affect 4 files, the second one affects 30 files)
continue installing as usual

**Comment by toupeira** [comment]
Thanks, fixed in bad898a.
