### ISSUE TITLE
Tags splited in letters in export HTML view

### ISSUE THREAD

**Issue by ubugnu** [projecthamster/hamster#215]
a picture is worth a thousand words
![Gestion%20du%20temps,%2030.01.2015.html](http://oi59.tinypic.com/2vubx4o.jpg)

**Comment by jessecfisher** [comment]
I also experience this.

I've created a partial solution.

Place this file:

https://github.com/jessecfisher/hamster/blob/9609811d8ad918ec27f3f7bb13d4550b1c35b04b/data/report_template.html

at:

    ~/.local/share/hamster-time-tracker/report_template.html

Please be mindful of if you have already created a custom `report_template.html` file at that location.

#### Note

Tags that contain spaces will be joined together.

For example, `work tools` will be displayed as `worktools`.

**Comment by gsobczyk** [comment]
I've already fix this: 1cb8d2fe23fec6d6bee3239512a62dc6c225a2b8
