### ISSUE TITLE
time Tracker fails to start

### ISSUE THREAD

**Issue by bellvk312** [projecthamster/hamster#217]
Ubuntu 14.04 64=bit
Installed Jan 14, 2015 from Software Center, hamster-applet 2.91.3+git20120514.b9fec3e1-1ubuntu1 
Been using it regularly, then today 02/04/2015 failed to start up.  no messages boxes or anything.  I click on icon and nothing.
I have 2 1/2 weeks of work reference materials, have supported Unix applicaitons and DB's, but relatively new Linux as desktop and administration.  Where is this installed, is there a log being kept for the applicaiton?  Where is it?  Is there a sysem log I should check?

**Comment by jessecfisher** [comment]
I believe your work should be saved in the following location:

    /home/<user>/.local/share/hamster-applet/hamster.db

I suggest you make a backup of that file before troubleshooting the issue.

I have some ideas...

1. Run `hamster` from the command line. Are there any error messages?

     $ hamster

2. Is `hamster-service` or `hamster` running? Check from the command line:

    $ ps aux | grep hamster

**Comment by bellvk312** [comment]
vkbell@opslnx3:/usr/bin$ ps aux| grep hamster
vkbell    3038  0.0  0.1 436560 24060 ?        Sl   08:16   0:00
/usr/bin/python /usr/lib/hamster-applet/hamster-service
vkbell    4166  0.0  0.0  11744   896 pts/11   S+   09:05   0:00 grep
--color=auto hamster

vkbell@opslnx3:~$ ls -l .local/share/hamster-applet
total 40
-rw-rw-r-- 1 vkbell vkbell 34816 Feb  3 17:35 hamster.db

vkbell@opslnx3:~$ pwd
/home/vkbell
vkbell@opslnx3:~$ hamster
hamster: command not found
vkbell@opslnx3:~$ which hamster
vkbell@opslnx3:~$

Recommendations on finding executable?

On Wed, Feb 4, 2015 at 6:48 PM, jessecfisher <notifications@github.com>
wrote:

> I believe your work should be saved in the following location:
>
> /home/<user>/.local/share/hamster-applet/hamster.db
>
> I suggest you make a backup of that file before troubleshooting the issue.
>
> I have some ideas...
>
>    1.
>
>    Run hamster from the command line. Are there any error messages?
>
>    $ hamster
>     2.
>
>    Is hamster-service or hamster running? Check from the command line:
>
>    $ ps aux | grep hamster
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthamster/hamster/issues/217#issuecomment-72965734>
> .
>



-- 
V Bell

**Comment by jessecfisher** [comment]
I am not very familiar with the Ubuntu Software Center, so this is just an idea..

Can you right click the hamster  launcher icon and view properties? 

Is there a hamster related .desktop file in either of these locations:

    /usr/share/applications/

    /home/vkbell/.local/share/applications/

If so, you can view it in a text editor, and look at the line labeled `Exec=`  to find the command it tries to run.

**Comment by bellvk312** [comment]
vkbell@opslnx3:~$ hamster-time-tracker
Traceback (most recent call last):
  File "/usr/bin/hamster-time-tracker", line 602, in <module>
    app = ProjectHamster()
  File "/usr/bin/hamster-time-tracker", line 110, in __init__
    self.init_workspace_tracking()
  File "/usr/bin/hamster-time-tracker", line 209, in init_workspace_tracking
    if not wnck: # can't track if we don't have the trackable
NameError: global name 'wnck' is not defined
vkbell@opslnx3:~$


Do you think I should kill hamster/time-tracker processes and attempt
restart?

vkbell@opslnx3:~$ ps -ef | grep hamster
vkbell    3038  2134  0 08:16 ?        00:00:00 /usr/bin/python
/usr/lib/hamster-applet/hamster-service
vkbell    7984  3643  0 15:54 pts/11   00:00:00 grep --color=auto hamster
vkbell    7989  3643  0 15:54 pts/11   00:00:00 grep --color=auto hamster


On Thu, Feb 5, 2015 at 3:29 PM, jessecfisher <notifications@github.com>
wrote:

> I am not very familiar with the Ubuntu Software Center, so this is just an
> idea..
>
> Can you right click the hamster launcher icon and view properties?
>
> Is there a hamster related .desktop file in either of these locations:
>
> /usr/share/applications/
>
> /home/vkbell/.local/share/applications/
>
> If so, you can view it in a text editor, and look at the line labeled
> Exec= to find the command it tries to run.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthamster/hamster/issues/217#issuecomment-73120539>
> .
>



-- 
V Bell

**Comment by jessecfisher** [comment]
> Do you think I should kill hamster/time-tracker processes and attempt
restart?

Yes, I think it is safe to do so. Be sure you have a backup of `hamster.db` though, just in case.

**Comment by bellvk312** [comment]
Still getting error involving definition of "wnck"

vkbell@opslnx3:~$ hamster-time-tracker
Traceback (most recent call last):
  File "/usr/bin/hamster-time-tracker", line 602, in <module>
    app = ProjectHamster()
  File "/usr/bin/hamster-time-tracker", line 110, in __init__
    self.init_workspace_tracking()
  File "/usr/bin/hamster-time-tracker", line 209, in init_workspace_tracking
    if not wnck: # can't track if we don't have the trackable
NameError: global name 'wnck' is not defined
vkbell@opslnx3:~$


Is this a failure or bad record in database while attempting to read?

On Thu, Feb 5, 2015 at 4:57 PM, jessecfisher <notifications@github.com>
wrote:

> Do you think I should kill hamster/time-tracker processes and attempt
> restart?
>
> Yes, I think it is safe to do so. Be sure you have a backup of hamster.db
> though, just in case.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthamster/hamster/issues/217#issuecomment-73138183>
> .
>



-- 
V Bell

**Comment by bellvk312** [comment]
Say, can I open the hamster.db file with, sya,..librebase?

On Thu, Feb 5, 2015 at 5:19 PM, Vernon Bell <bellvkg@gmail.com> wrote:

> Still getting error involving definition of "wnck"
>
> vkbell@opslnx3:~$ hamster-time-tracker
> Traceback (most recent call last):
>   File "/usr/bin/hamster-time-tracker", line 602, in <module>
>     app = ProjectHamster()
>   File "/usr/bin/hamster-time-tracker", line 110, in __init__
>     self.init_workspace_tracking()
>   File "/usr/bin/hamster-time-tracker", line 209, in
> init_workspace_tracking
>     if not wnck: # can't track if we don't have the trackable
> NameError: global name 'wnck' is not defined
> vkbell@opslnx3:~$
>
>
> Is this a failure or bad record in database while attempting to read?
>
> On Thu, Feb 5, 2015 at 4:57 PM, jessecfisher <notifications@github.com>
> wrote:
>
>> Do you think I should kill hamster/time-tracker processes and attempt
>> restart?
>>
>> Yes, I think it is safe to do so. Be sure you have a backup of hamster.db
>> though, just in case.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/projecthamster/hamster/issues/217#issuecomment-73138183>
>> .
>>
>
>
>
> --
> V Bell
>



-- 
V Bell

**Comment by jessecfisher** [comment]
> Still getting error involving definition of "wnck"

I don't know how to proceed with that. Hopefully someone more experienced can help.

>Say, can I open the hamster.db file with, say,..librebase?

I think `hamster.db` is a Sqlite database. LibreBase can't open it directly.  
Alternatively, this looks like a good solution to browse the db http://sqlitebrowser.org/

**Comment by bellvk312** [comment]
Booted up today and attempted to start time tracker afer uninstalling it
and reinstalling it using Ubuntu Software Center.

Here is the ubuntu system error I am getting.  I think I need to uninstall,
do some manual clean up in the install directory, then try to re-install.


Any recommendations of where I might find and  should delete any residual
modules installed?

On Thu, Feb 5, 2015 at 5:33 PM, jessecfisher <notifications@github.com>
wrote:

> Still getting error involving definition of "wnck"
>
> I don't know how to proceed with that. Hopefully someone more experienced
> can help.
>
> Say, can I open the hamster.db file with, say,..librebase?
>
> I think hamster.db is a Sqlite database. LibreBase can't open it directly.
>
> Alternatively, this looks like a good solution to browse the db
> http://sqlitebrowser.org/
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthamster/hamster/issues/217#issuecomment-73144498>
> .
>



-- 
V Bell

**Comment by toupeira** [comment]
Closing this, feel free to reopen if you still experience this issue with current master.
