### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by umpirsky** [projecthamster/hamster#219]
It is missing HiDPI display support (Time Tracker 2.91.3). Font sizes are not good, for example, small font in task list.

**Comment by toupeira** [comment]
I think you're using the old Gtk2 version, the current Git master (version ~1.04) looks fine here on Gnome 3 and a 3200x1800 screen.

**Comment by umpirsky** [comment]
@toupeira Thanks for quick response.

Here is what I have installed:

```
$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64                                      3.10.8-0ubuntu1.4                                   amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                                          3.10.8-0ubuntu1.4                                   amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common                                       3.10.8-0ubuntu1.4                                   all          common files for the GTK+ graphical user interface library
ii  libgtk2.0-0:amd64                                     2.24.23-0ubuntu1.1                                  amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                                         2.24.23-0ubuntu1.1                                  amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-common                                      2.24.23-0ubuntu1.1                                  all          common files for the GTK+ graphical user interface library
```

Should it work?

**Comment by toupeira** [comment]
See the [README](https://github.com/projecthamster/hamster#dependencies) for the required dependencies. The packages available from distributions are outdated, you currently need to clone the Git repository and follow the installation instructions in the README.

**Comment by umpirsky** [comment]
@toupeira OK, thanks. Will wait for distributions to update gtk.

**Comment by toupeira** [comment]
Sorry if I wasn't clear, it's Hamster that needs to be upgraded (the current version uses Gtk3), not Gtk itself.

**Comment by umpirsky** [comment]
@toupeira Oh, ok, clear now. Do you have any information regarding Ubuntu Software Center update, when will new version be available in it? Thanks.

**Comment by toupeira** [comment]
Well the project was unmaintained for a while, and I'm not really doing a great job at it either ;-) So the situation currently is that nobody's building updated packages, but we'll try to get this going again over the next few months.

But there's the `checkinstall` package which can build packages out of install scripts, so you can tweak the installation instructions like this:

```bash
./waf configure build --prefix=/usr/local
sudo checkinstall ./waf install
```

And it will create a local package that you can easily uninstall.
