### ISSUE TITLE
 put a daily total on the add activity form

### ISSUE THREAD

**Issue by tstriker** [projecthamster/hamster#22]
original: https://bugzilla.gnome.org/show_bug.cgi?id=663407

**Comment by cweiske** [comment]
+1

**Comment by fturco** [comment]
I also prefer to check how much time I spent overall on all tasks on a certain day.

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

If you are still interested in working on the new codebase (repositories: hamster-lib/cli/gtk/dbus) we would be most thrilled. Please feel free to either open a new issue with the relevant repository and/or join the discussion on the [mailinglist](http://lists.projecthamster.org/listinfo.cgi/hamster-dev-projecthamster.org).
For more context please see our [website](http://projecthamster.org).

Thanks for your interest and support! Eric.
