### ISSUE TITLE
ImportError: No module named hamster

### ISSUE THREAD

**Issue by auipga** [projecthamster/hamster#221]
Using Arch Linux
```
$ uname -a
Linux auipga 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux
```
Installed dependencies:
```
python-dbus python-xdg gnome-control-center python2-libgnome python2-gconf python2-gnomecanvas python2-wnck intltool gnome-doc-utils docbook2x
python2-pysqlite (from AUR)
```
```
$ ./waf configure build --prefix=/usr/local
Checking for program python              : /usr/sbin/python2 
Checking for Python version >= 2.4.2     : ok 2.7.9 
Checking for program glib-genmarshal     : /usr/sbin/glib-genmarshal 
Checking for program glib-mkenums        : /usr/sbin/glib-mkenums 
Checking for program dbus-binding-tool   : /usr/sbin/dbus-binding-tool 
Checking for program docbook2man         : /usr/sbin/docbook2man 
Checking for program xml2po              : /usr/sbin/xml2po 
Checking for program xsltproc            : /usr/sbin/xsltproc 
Checking for program msgfmt              : /usr/sbin/msgfmt 
Checking for program intltool-merge      : /usr/sbin/intltool-merge 
Checking for program xml2po              : /usr/sbin/xml2po 
'configure' finished successfully (0.041s)
Waf: Entering directory `/home/auipga/hamster/build'
( files 1 to 200, everything looks ok )
Generating and caching the translation database
Merging translations into default/data/hamster-time-tracker.schemas.
Waf: Leaving directory `/home/auipga/hamster/build'
'build' finished successfully (3.405s)
```
```
$ sudo ./waf install
(ends with)
'install' finished successfully (0.154s)
```

Till now everithing looks ok.
Running hamster fails.
```
$ hamster
Traceback (most recent call last):
  File "/usr/local/bin/hamster", line 30, in <module>
    from hamster import client, reports
ImportError: No module named hamster
```

**Comment by toupeira** [comment]
Please try again with `sudo ./waf install`.

**Comment by auipga** [comment]
I did. (changed the first post)

**Comment by billyworm** [comment]
I think have the (quite) same issue with Ubuntu 14.04:

``` $ uname -a
Linux rynn-lt 3.13.0-46-generic #76-Ubuntu SMP Thu Feb 26 18:52:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux ```

Installed all dependencies.
Build finished successfully.
Installation  (with sudo) finished successfully.


``` $ hamster```
```Traceback (most recent call last):```
 ``` File "/usr/bin/hamster", line 30, in <module>```
 ```   from hamster import client, reports```
```ImportError: cannot import name client ```

**Comment by auipga** [comment]
Maybe it is important to note:
```sh
$ python --version
Python 3.4.3
$ python2 --version
Python 2.7.9
```
Is this still relevant after https://github.com/projecthamster/hamster/commit/bad898a86b14260e8ef95566d3c4cc05de6dd251?

**Comment by ameenross** [comment]
Getting the same error on FC21

**Comment by ameenross** [comment]
I had to do the following to fix this error:

```bash
$ export PYTHONPATH=/usr/local/lib/python2.7/site-packages
```

See http://stackoverflow.com/questions/338768/python-importerror-no-module-named

Now I'm getting another error though.

**Comment by ameenross** [comment]
It probably complains now because `hamster-service` and `hamster-window-service` have the same issue. `hamster` tries to processes for these services. When I start these processes manually with the proper `PYTHONPATH` set locally, I can start hamster. I just seem to have a problem with an old DB scheme.

**Comment by ameenross** [comment]
I finally just installed with:

```sh
./waf configure build --prefix=/usr
sudo ./waf install
```

No more import issues due to path problems.

**Comment by auipga** [comment]
can confirm this.
but now I get a new error https://github.com/projecthamster/hamster/issues/231

**Comment by marshwiggle** [comment]
I have the same error with the latest version of hamster.

OS: Linux Mint 18.3 Cinnamon 64-bit
Python version: 2.7.12
Python3 version: 3.5.2

**Comment by ederag** [comment]
@marshwiggle which version exactly (1.04, 2.1.1, master, ...) ?
Are you following [these instructions](https://github.com/projecthamster/hamster#building-and-installing) ?

**Comment by marshwiggle** [comment]
Hi, @ederag!

This is the version I use:

`+ hamster $ git show --summary
commit 5fcdfa503c35a10795b2d4a79578222a1b5b1303
Author: ederag <edera@gmx.fr>
Date:   Mon Feb 4 20:12:35 2019 +0100

    test for decimal number in activity (#386)
`

And this is my installation log:

`
+ hamster $ ./waf configure build --prefix=/usr && sudo ./waf install
Checking for program python              : /usr/bin/python2 
Checking for Python version >= 2.4.2     : ok 2.7.12 
Checking for program glib-genmarshal     : /usr/bin/glib-genmarshal 
Checking for program glib-mkenums        : /usr/bin/glib-mkenums 
Checking for program dbus-binding-tool   : not found 
Checking for program docbook2man         : not found 
Checking for program xml2po              : not found 
Checking for program xsltproc            : /usr/bin/xsltproc 
Checking for program msgfmt              : /usr/bin/msgfmt 
Checking for program intltool-merge      : /usr/bin/intltool-merge 
Checking for program xml2po              : not found 
'configure' finished successfully (0.145s)
Waf: Entering directory `/home/simeon/Incoming/hamster/build'
Waf: Leaving directory `/home/simeon/Incoming/hamster/build'
'build' finished successfully (0.039s)
Waf: Entering directory `/home/simeon/Incoming/hamster/build'
* installing src/hamster-service as /usr/lib/hamster-time-tracker/hamster-service
* installing src/hamster-windows-service as /usr/lib/hamster-time-tracker/hamster-windows-service
* installing src/hamster-cli as /usr/bin/hamster
* installing src/hamster.bash as /etc/bash_completion.d/hamster.bash
* installing src/hamster/client.py as /usr/lib/python2.7/dist-packages/hamster/client.py
* installing src/hamster/overview.py as /usr/lib/python2.7/dist-packages/hamster/overview.py
* installing src/hamster/__init__.py as /usr/lib/python2.7/dist-packages/hamster/__init__.py
* installing src/hamster/reports.py as /usr/lib/python2.7/dist-packages/hamster/reports.py
* installing src/hamster/edit_activity.py as /usr/lib/python2.7/dist-packages/hamster/edit_activity.py
* installing src/hamster/idle.py as /usr/lib/python2.7/dist-packages/hamster/idle.py
* installing src/hamster/about.py as /usr/lib/python2.7/dist-packages/hamster/about.py
* installing src/hamster/external.py as /usr/lib/python2.7/dist-packages/hamster/external.py
* installing src/hamster/preferences.py as /usr/lib/python2.7/dist-packages/hamster/preferences.py
* installing src/hamster/lib/configuration.py as /usr/lib/python2.7/dist-packages/hamster/lib/configuration.py
* installing src/hamster/lib/pytweener.py as /usr/lib/python2.7/dist-packages/hamster/lib/pytweener.py
* installing src/hamster/lib/stuff.py as /usr/lib/python2.7/dist-packages/hamster/lib/stuff.py
* installing src/hamster/lib/desktop.py as /usr/lib/python2.7/dist-packages/hamster/lib/desktop.py
* installing src/hamster/lib/charting.py as /usr/lib/python2.7/dist-packages/hamster/lib/charting.py
* installing src/hamster/lib/layout.py as /usr/lib/python2.7/dist-packages/hamster/lib/layout.py
* installing src/hamster/lib/__init__.py as /usr/lib/python2.7/dist-packages/hamster/lib/__init__.py
* installing src/hamster/lib/i18n.py as /usr/lib/python2.7/dist-packages/hamster/lib/i18n.py
* installing src/hamster/lib/graphics.py as /usr/lib/python2.7/dist-packages/hamster/lib/graphics.py
* installing src/hamster/lib/trophies.py as /usr/lib/python2.7/dist-packages/hamster/lib/trophies.py
* installing src/hamster/storage/__init__.py as /usr/lib/python2.7/dist-packages/hamster/storage/__init__.py
* installing src/hamster/storage/storage.py as /usr/lib/python2.7/dist-packages/hamster/storage/storage.py
* installing src/hamster/storage/db.py as /usr/lib/python2.7/dist-packages/hamster/storage/db.py
* installing src/hamster/widgets/activityentry.py as /usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py
* installing src/hamster/widgets/__init__.py as /usr/lib/python2.7/dist-packages/hamster/widgets/__init__.py
* installing src/hamster/widgets/reportchooserdialog.py as /usr/lib/python2.7/dist-packages/hamster/widgets/reportchooserdialog.py
* installing src/hamster/widgets/tags.py as /usr/lib/python2.7/dist-packages/hamster/widgets/tags.py
* installing src/hamster/widgets/dayline.py as /usr/lib/python2.7/dist-packages/hamster/widgets/dayline.py
* installing src/hamster/widgets/dates.py as /usr/lib/python2.7/dist-packages/hamster/widgets/dates.py
* installing src/hamster/widgets/facttree.py as /usr/lib/python2.7/dist-packages/hamster/widgets/facttree.py
* installing src/hamster/widgets/timeinput.py as /usr/lib/python2.7/dist-packages/hamster/widgets/timeinput.py
* installing data/stats.ui as /usr/share/hamster-time-tracker/stats.ui
* installing data/preferences.ui as /usr/share/hamster-time-tracker/preferences.ui
* installing data/edit_activity.ui as /usr/share/hamster-time-tracker/edit_activity.ui
* installing data/date_range.ui as /usr/share/hamster-time-tracker/date_range.ui
* installing data/hamster.db as /usr/share/hamster-time-tracker/hamster.db
* installing data/art/stock_calendar-view-day.png as /usr/share/hamster-time-tracker/art/stock_calendar-view-day.png
* installing data/art/stock_calendar-view-month.png as /usr/share/hamster-time-tracker/art/stock_calendar-view-month.png
* installing data/art/hamster-time-tracker.png as /usr/share/hamster-time-tracker/art/hamster-time-tracker.png
* installing data/art/stock_calendar-view-week.png as /usr/share/hamster-time-tracker/art/stock_calendar-view-week.png
* installing data/report_template.html as /usr/share/hamster-time-tracker/report_template.html
* installing data/art/16x16/hamster-time-tracker.png as /usr/share/icons/hicolor/16x16/apps/hamster-time-tracker.png
* installing data/art/22x22/hamster-time-tracker.png as /usr/share/icons/hicolor/22x22/apps/hamster-time-tracker.png
* installing data/art/32x32/hamster-time-tracker.png as /usr/share/icons/hicolor/32x32/apps/hamster-time-tracker.png
* installing data/art/scalable/hamster-time-tracker.png as /usr/share/icons/hicolor/48x48/apps/hamster-time-tracker.png
* installing data/art/scalable/hamster-time-tracker.svg as /usr/share/icons/hicolor/scalable/apps/hamster-time-tracker.svg
* installing build/default/src/hamster/defs.py as /usr/lib/python2.7/dist-packages/hamster/defs.py
* installing build/default/org.gnome.hamster.service as /usr/share/dbus-1/services/org.gnome.hamster.service
* installing build/default/org.gnome.hamster.Windows.service as /usr/share/dbus-1/services/org.gnome.hamster.Windows.service
* installing build/default/po/af.mo as /usr/share/locale/af/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ar.mo as /usr/share/locale/ar/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/as.mo as /usr/share/locale/as/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/be.mo as /usr/share/locale/be/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/bg.mo as /usr/share/locale/bg/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/bn.mo as /usr/share/locale/bn/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/bn_IN.mo as /usr/share/locale/bn_IN/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ca.mo as /usr/share/locale/ca/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ca@valencia.mo as /usr/share/locale/ca@valencia/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/cs.mo as /usr/share/locale/cs/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/da.mo as /usr/share/locale/da/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/de.mo as /usr/share/locale/de/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/el.mo as /usr/share/locale/el/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/en_CA.mo as /usr/share/locale/en_CA/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/en_GB.mo as /usr/share/locale/en_GB/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/en@shaw.mo as /usr/share/locale/en@shaw/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/eo.mo as /usr/share/locale/eo/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/es.mo as /usr/share/locale/es/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/et.mo as /usr/share/locale/et/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/eu.mo as /usr/share/locale/eu/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/fi.mo as /usr/share/locale/fi/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/fr.mo as /usr/share/locale/fr/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/gl.mo as /usr/share/locale/gl/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/gu.mo as /usr/share/locale/gu/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/he.mo as /usr/share/locale/he/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/hi.mo as /usr/share/locale/hi/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/hu.mo as /usr/share/locale/hu/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/id.mo as /usr/share/locale/id/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/it.mo as /usr/share/locale/it/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ja.mo as /usr/share/locale/ja/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/kn.mo as /usr/share/locale/kn/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ko.mo as /usr/share/locale/ko/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ku.mo as /usr/share/locale/ku/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/lt.mo as /usr/share/locale/lt/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/lv.mo as /usr/share/locale/lv/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/mai.mo as /usr/share/locale/mai/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/mk.mo as /usr/share/locale/mk/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ml.mo as /usr/share/locale/ml/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/mr.mo as /usr/share/locale/mr/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/nb.mo as /usr/share/locale/nb/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/nl.mo as /usr/share/locale/nl/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/or.mo as /usr/share/locale/or/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/pa.mo as /usr/share/locale/pa/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/pl.mo as /usr/share/locale/pl/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/pt.mo as /usr/share/locale/pt/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/pt_BR.mo as /usr/share/locale/pt_BR/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ro.mo as /usr/share/locale/ro/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ru.mo as /usr/share/locale/ru/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/si.mo as /usr/share/locale/si/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/sl.mo as /usr/share/locale/sl/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/sq.mo as /usr/share/locale/sq/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/sr.mo as /usr/share/locale/sr/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/sr@latin.mo as /usr/share/locale/sr@latin/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/sv.mo as /usr/share/locale/sv/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ta.mo as /usr/share/locale/ta/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/te.mo as /usr/share/locale/te/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/th.mo as /usr/share/locale/th/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/tr.mo as /usr/share/locale/tr/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/ug.mo as /usr/share/locale/ug/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/uk.mo as /usr/share/locale/uk/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/vi.mo as /usr/share/locale/vi/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/zh_CN.mo as /usr/share/locale/zh_CN/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/zh_HK.mo as /usr/share/locale/zh_HK/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/po/zh_TW.mo as /usr/share/locale/zh_TW/LC_MESSAGES/hamster-time-tracker.mo
* installing build/default/data/hamster-time-tracker.schemas as /etc/gconf/schemas/hamster-time-tracker.schemas
* installing build/default/data/hamster-time-tracker-overview.desktop as /usr/share/applications/hamster-time-tracker-overview.desktop
* installing build/default/data/hamster-time-tracker.desktop as /usr/share/applications/hamster-time-tracker.desktop
* installing build/default/data/hamster-windows-service.desktop as /usr/share/applications/hamster-windows-service.desktop
Waf: Leaving directory `/home/simeon/Incoming/hamster/build'
Installing GConf schema 
Updating Gtk icon cache. 
'install' finished successfully (1.627s)
`

**Comment by ederag** [comment]
Thanks for the precise version, latest indeed.
The build log seems fine.
Did you follow [these instructions](https://github.com/projecthamster/hamster#building-and-installing) ?
Moving the hamster directory from the python2 to your correct python3 directory is very important.

**Comment by marshwiggle** [comment]
Hi, @ederag!

Yes, I've tried to do what you told me, but I had to change `usr/lib/python2.7/site-packages/hamster` to `usr/lib/python2.7/dist-packages/hamster`, as the installation script puts the files to `dist-package` rather than to `site-packages`. Unfortunately, I've got the same error:

```
+ ~ $ hamster 
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
ImportError: No module named 'hamster'
```
Btw, these are my python versions:
```
+ hamster $ python --version
Python 2.7.12
+ hamster $ python3 --version
Python 3.5.2
```

**Comment by ederag** [comment]
Please give the exact full commands used to install (to move from 2.7 to 3.5).

**Comment by marshwiggle** [comment]
```
+ hamster $ ./waf configure build --prefix=/usr && sudo ./waf install
+ hamster $ sudo rm -rf /usr/lib/python3.5/site-packages/hamster/
+ hamster $ sudo mv /usr/lib/python2.7/dist-packages/hamster/ /usr/lib/python3.5/site-packages/

```
Output of `python3 -c "import site; print(site.getsitepackages())"`:

`
['/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.5/dist-packages']

`

**Comment by ederag** [comment]
As the instructions said,
> Adapt the paths below to your system

In your case, `site-packages` should be changed with `dist-packages`:
```
sudo mv /usr/lib/python2.7/dist-packages/hamster/ /usr/lib/python3.5/dist-packages
```

Thanks for giving more informations though, that might help others figuring out the issue as well.
Until we migrate to `setuptools` for installation, or the rewrite is stable.

**Comment by marshwiggle** [comment]
Hi, @ederag!

Thak you for your help!

I've changed the path.  These is how my installation process looks like now:
```
+ hamster $ sudo ./waf uninstall
+ hamster $ ./waf configure build --prefix=/usr && sudo ./waf install
+ hamster $ sudo rm -rf /usr/lib/python3.5/dist-packages/hamster
+ hamster $  sudo mv /usr/lib/python2.7/dist-packages/hamster/ /usr/lib/python3.5/dist-packages/
+ hamster $ ls /usr/lib/python3.5/dist-packages/hamster/
about.py   edit_activity.py  __init__.py  preferences.py  widgets
client.py  external.py       lib          reports.py
defs.py    idle.py           overview.py  storage
```
So, the installation seems to be successeful. Unfortunately, when I type `hamster` in the command prompt I get a new error:
```
+ ~ $ hamster
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
  File "/usr/lib/python3.5/dist-packages/hamster/reports.py", line 131
    """
      ^
SyntaxError: invalid syntax
```
So, there is a problem in the `reports.py`. I don't understand why, but when I comment out the following lines, everything works like a charm:
```
        event_str = f"""\
                     BEGIN:VEVENT
                     CATEGORIES:{fact.category}
                     DTSTART:{fact.start_time}
                     DTEND:{fact.end_time}
                     SUMMARY:{fact.activity}
                     DESCRIPTION:{fact.description}
                     END:VEVENT
                     """
```
Finally, I've got a main window, but have no idea of how to add my current task. :(

![2019-02-10 16-24-40](https://user-images.githubusercontent.com/11543851/52534290-c1965800-2d50-11e9-99b1-5133ee30e6dd.png)

**Comment by ederag** [comment]
To create a new task, hit the `+` button in the header.
The new error is because you have python-3.5.
Since the error is different, could you please file a new issue,
copying the relevant informations ?

**Comment by marshwiggle** [comment]
@ederag 

You wrote: "To create a new task, hit the `+` button in the header."

This is the exactly what I do but there are only few of my tasks in the autocompletion drow-down. Most of them are hidden. :(

**Comment by sweng5080** [comment]
On Ubuntu 20.04.6 with Python 3.8.10 as the default I was able to fix the issue by setting the environment variable for the PYTHONDIR as part of the waf configuration:
`PYTHONDIR=/usr/lib/python3.8/dist-packages ./waf configure`

The problem appears to be with python3 distutils.sysconfig.get_python_lib() returning `/usr/lib/python3.8/site-packages` which gets utilized in waflib/Tools/python.py in check_python_version() to configure the PYTHONDIR, that will get used for the installation of the python files. By setting the environment variable, check_python_version() will pick up the specified value and use it for the installation instead of the path returned through distutils.sysconfig.get_python_lib().
