### ISSUE TITLE
Report problems

### ISSUE THREAD

**Issue by jgribonvald** [projecthamster/hamster#228]
Hello I'm having problems in report generated (I'm using dayli builds on ubuntu 14.04.1 - unity)
I checked in the UI if there were something wrong but not... 

![selection_018](https://cloud.githubusercontent.com/assets/1597283/7062729/7d8cb4ea-dea0-11e4-91da-10a647321d74.png)

Can i do something to solve that ?

**Comment by jgribonvald** [comment]
Ok I found the problem, i had some activity without end. I think it's done when i shutdown and that i don't close my activity. Is there a way to automaticaly end an activity when hamster close ? Also maybe this can be due to a crash ?

**Comment by nchachereau** [comment]
>  I think it's done when i shutdown and that i don't close my activity. Is there a way to automatically end an activity when hamster close ?

See Tracking settings: Stop tracking on shutdown.

**Comment by jgribonvald** [comment]
Thanks
