### ISSUE TITLE
Text color problem

### ISSUE THREAD

**Issue by jgribonvald** [projecthamster/hamster#229]
Hello,
I have a bad color on Sums texts, I'm on ubuntu 14.04.1 with unity and i use daily builds see on the attached file
![selection_019](https://cloud.githubusercontent.com/assets/1597283/7062797/0c9f89a0-dea1-11e4-939d-e855022dcd38.png)

How to solve this problem ?

**Comment by nchachereau** [comment]
I have never seen this, using Ubuntu 15.04. What unity theme are you using?

**Comment by jgribonvald** [comment]
thème : ambiance
icon : ubuntu-mono-dark

**Comment by helmo** [comment]
I have the same issue.
I also tried the high contrast theme ... that makes it a bit better readable.
![hamster-windows-service_017](https://cloud.githubusercontent.com/assets/104120/12941928/6944f258-cfd7-11e5-9da9-9103868cb44d.png)

This seems related to #164

**Comment by ederag** [comment]
Thanks for the clear report.
Should be fixed by PR #391.
Please test and give feedback there !
