### ISSUE TITLE
It doesn’t seem possible to hack on this locally

### ISSUE THREAD

**Issue by Profpatsch** [projecthamster/hamster#233]
I’d like to hack on hamster without having to install it into my system first (and delete the repo version), but I can’t see any good method where I can be sure no old dependencies are used.

How can I do it? Can some devs document how their workflows?

**Comment by ederag** [comment]
Thanks for your interest.
Documentation can now be found here:
https://github.com/projecthamster/hamster#trying-the-development-version
Please note that this is legacy hamster. Little patches might be accepted, but
future development should go to [hamster-gtk](https://github.com/projecthamster/hamster-gtk).
