### ISSUE TITLE
Hamster list should be line-based

### ISSUE THREAD

**Issue by Profpatsch** [projecthamster/hamster#234]
Because it displays the task name on a second line it is awkward to grep.

**Comment by Profpatsch** [comment]
Hm, `hamster export tsv` seems to do a better job at that, but what is the use `list` then anyway?

**Comment by ederag** [comment]
Task name is now on a single line. Tested with [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1):
```
Start | End   | Duration | Activity     | Category    
---------------------------------------------------------
19:27 |       | 1h 3min  | freeSoftware | diffusion 
```

**Comment by Profpatsch** [comment]
Haha, great to see this project is active again.
