### ISSUE TITLE
Unable to remove tags

### ISSUE THREAD

**Issue by Forage** [projecthamster/hamster#238]
Sometimes you get unwanted tags because of a typo, especially because tags don't get auto-completed in the GNOME extension (bug #114 and #12), or simply because you change your mind afterwards. The result is tags you can't remove any more, despite an option to remove tags from the complete field. Removing tags from this field in the preferences still presents all of them again when you return to the list.

Steps to reproduce:
1. Add activity through the extension "reading e-mail@work, #pita"
2. Add activity through the extension "poo@work, #relieve"
3. Open the preferences through "Tracker settings" option in the extension and go to the "Categories and Tags" tab
4. Remove "pita" from the auto-complete list
5. Close the preferences and repeat step 3.

Result:
1. The tag "pita" is still present in the auto-complete list

This happens for tags that are being used for existing activities as well as non-used tags because you changed/fixed them by altering an existing activity.

OS: Ubuntu 14.04
Hamster: 3.0really1.03.3+git2370-0dylanmccall1~ubuntu14.04.1 from https://launchpad.net/~dylanmccall/+archive/ubuntu/hamster-time-tracker-git-stable

Let me know if you need any more information.

**Comment by Johann-Tree** [comment]
I have the same issue here, very annoying: It created several wrong tags from wrong auto-completion. Until this is fixed I directly edit the database via SQLite Manager (e.g. for Firefox https://addons.mozilla.org/firefox/addon/sqlite-manager ). This works ok.

**Comment by orschiro** [comment]
For Ubuntu Linux users I recommend http://sqlitebrowser.org/.

**Comment by ederag** [comment]
In current master (d86e07fc6550f53713917d6308584400c8bdbbc3) the tags can be removed, provided they do not appear in an existing fact.
So totally wrong tags can be removed (just fix the wrong fact first).

But still it should be possible to remove a tag, whether it is present in a fact or not.

**Comment by ederag** [comment]
Should be fully fixed by #487 (thanks @GeraldJansen !).
