### ISSUE TITLE
Report fails when localized date contains non-ASCII characters (e.g. Février)

### ISSUE THREAD

**Issue by jgribonvald** [projecthamster/hamster#239]
I'm having problems to generate a report for "Février" (February) month, and I'm having the same problem for any day on this month. Do you think that can be due to french month name with accents ?

Any help to resolve for this bug would be appreciated.

Thanks

**Comment by nchachereau** [comment]
> Do you think that can be due to french month name with accents ?

Unfortunately, yes, it does. (`hamster export 2015-02-01 2015-02-28` will show you the error). Unicode was difficult to handle in Python2, and Hamster does not do it very well. (See also #153).

I have started looking into this. In the meantime, if this is urgent, you could try doing the same as pull request #218 : adding the following lines near the start of reports.py

```py
reload(sys)
sys.setdefaultencoding("utf-8")
```

**Comment by jgribonvald** [comment]
Thanks, #218 is solving the problem !

**Comment by ederag** [comment]
Thanks a lot.
This utf-8 issue has hopefully been fixed by the [python3 migration](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
