### ISSUE TITLE
Gnome Shell doesn't associate windows with application

### ISSUE THREAD

**Issue by CendioOssman** [projecthamster/hamster#242]
I have the hamster window as a favourite in Gnome Shell. Unfortunately opening hamster gives me a second entry on the dock. I would guess that hamster is not setting its window properties properly to let Gnome Shell associate the window with the .desktop file. I believe it is WM_CLASS that needs to be set to the same name as the .desktop file.

**Comment by ederag** [comment]
Thanks for the report.
Probably a good pointer ?
https://stackoverflow.com/q/20907897/3565696

**Comment by ederag** [comment]
Is #516 fixing this ?
