### ISSUE TITLE
Workrave integration

### ISSUE THREAD

**Issue by eliotb** [projecthamster/hamster#246]
The workrave app http://www.workrave.org/  monitors activity and prompts user to take micro and rest breaks.  It would be cool if hamster cooperated with this to (optionally of course)
- ask whether current task is still correct on resumption from micro or rest breaks
- pause timing during rest break

**Comment by wehlutyk** [comment]
Any idea on what priority this can be given? I'd be very interested in such a feature!

**Comment by FelixSchwarz** [comment]
Not sure if this tracker is the right place to ask for Workrave support. IIRC Hamster already uses DBUS to "announce" changes in working time so Workrave should be able to listen for these messages. (Disclaimer: I'm by no means familiar with the Hamster code)

**Comment by wehlutyk** [comment]
Thanks for the tip! @rcaelers does this make sense? (no issues available on the workrave repo)

**Comment by FelixSchwarz** [comment]
@wehlutyk workrave has an issue tracker (Bugzilla, http://issues.workrave.org/), even though I suggest (just from general open source experience) you try the mailing list (https://lists.sourceforge.net/lists/listinfo/workrave-user) first.

**Comment by wehlutyk** [comment]
@FelixSchwarz my bad, will do. Thanks :)
