### ISSUE TITLE
Day starts at 02:00:01

### ISSUE THREAD

**Issue by nick-lehmann** [projecthamster/hamster#248]
I am using Hamster 2.91.3 on Ubuntu 15.04. It seems like it is not possible to add an Earlier Activity that started before 02:00:00. I tried it using both the GUI and the `hamster-cli start`. But when the starting time of the activity is set to 02:00:01 adding work fine.

**Comment by ederag** [comment]
This should be fixed since [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
Leaving open, with the hamster-applet label.

**Comment by ederag** [comment]
Closing, since this issue is thought to be solved in the development version.
(the meaning of the hamster-applet label has been [changed](https://github.com/projecthamster/hamster/issues/312#issuecomment-521266921))
Thanks for contributing to hamster improvement !
