### ISSUE TITLE
Activity ends up in 8.668833633433529e+31 hours

### ISSUE THREAD

**Issue by jorgb** [projecthamster/hamster#250]
The regular GUI shows me 5 hours, 9 mins for this project, but when I export this to an HTML file, the time shows up as an insanely large number; 8.668833633433529e+31

Also, the total amount of hours for this week is; 
   Activity report for August 23 – 29, 2015 (8.668833633433432e+56)

![2015-08-27-104514](https://cloud.githubusercontent.com/assets/3519707/9516481/31ef8c0c-4ca9-11e5-9dd2-3f45900fb115.png)

**Comment by jorgb** [comment]
This seems to be happening when the time is incorrectly set, for example; 10:30 10:30 Activity@Project
which should result in 0, but turns into an insanely large number.

**Comment by ederag** [comment]
Seems to not occur in current master (2be328f).
Leaving open with the hamster-applet label.

**Comment by ederag** [comment]
Closing, since this issue is thought to be solved in the development version.
(the meaning of the hamster-applet label has been [changed](https://github.com/projecthamster/hamster/issues/312#issuecomment-521266921))
Thanks for contributing to hamster improvement !
