### ISSUE TITLE
Enter a time from the future

### ISSUE THREAD

**Issue by maltris** [projecthamster/hamster#255]
It would be great if it was possible to enter a time from the future. 

For example: If on friday 3 pm I start a task that is taking me until 4 pm and after it is done i'll leave without going to the computer again.

With 2.91.3 at Ubuntu 14.04 this is not possible because if I enter a time from the future, it jumps back to the current time.

**Comment by ederag** [comment]
Closing, since the original use case is now solved. Please comment here
if being able to set a date later than today would be important.
(currently the editor window stops at today, which is kind of a security)
Thanks for contributing to hamster improvement !
