### ISSUE TITLE
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by efender** [projecthamster/hamster#257]
I have similar issue to #68 but another code:
```bash
Traceback (most recent call last):
  File "/usr/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.257 was not provided by any .service files
```
/usr/lib/hamster-time-tracker/hamster-service
```bash
hamster-service up
Segmentation fault (core dumped)
```
Ubuntu 15.10 (minimal installation + cinnamon)
Hamster from repo (2.0-rc1-2)

**Comment by efender** [comment]
I've installed Kubuntu 15.10 beta2 and hamster works now (from  repo).
Sorry!

**Comment by Chouchen** [comment]
Still doesn't work on Ubuntu with Gnome though. See #263 ...

**Comment by hacrot3000** [comment]
I got same problem on Fedora 23 after update some package today. It was work well before update. 

The update log show:
>    Upgraded hamster-time-tracker-1.04-5.fc23.noarch                      (unknown)
 >   Upgrade                       2.0-0.2.rc1.fc23.noarch                 @updates

Run hamster command I got:

> [duongtc@duong-tc ~]$ hamster
> /usr/lib/python2.7/site-packages/hamster/lib/stuff.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk as gtk
> /usr/lib/python2.7/site-packages/hamster/lib/configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
>   from gi.repository import GConf as gconf
> Traceback (most recent call last):
>   File "/usr/bin/hamster", line 387, in <module>
>     hamster_client.overview()
>   File "/usr/bin/hamster", line 152, in overview
>     self._launch_window("overview")
>   File "/usr/bin/hamster", line 143, in _launch_window
>     getattr(server, window_name)()
>   File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
>     return self._proxy_method(*args, **keywords)
>   File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.159 was not provided by any .service files
> 

Run /usr/bin/hamster-service I got:

> /usr/lib/python2.7/site-packages/hamster/lib/stuff.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk as gtk
> /usr/lib/python2.7/site-packages/hamster/idle.py:24: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
>   from gi.repository import GConf as gconf
> hamster-service up
> Segmentation fault (core dumped)
> 

I downgrade hamster-time-tracker back to and it is back. I will now disable any update for hamster-time-tracker :)
