### ISSUE TITLE
hamster-cli list doesn't see activities between midnight and "start of day"

### ISSUE THREAD

**Issue by losvald** [projecthamster/hamster#260]
How to reproduce:

1) Set "New day starts at" to some value after midnight
2) Start an activity after mednight but before the beginning of the new day
3) Optionally, end the activity. (Doesn't matter since hamster-cli shows even the one in progress.)
4) Run: `hamster-cli -H:00` within H hours of starting the last activity, but before the beginning of the new day.
5) Run: `hamster-cli <time_before_start_but_after_midnight>`

Symptoms:
- Both 4) (using relative time) and 5) (using absolute time) shows none of the activities started after midnight but before the beginnin of a new day.
- Activities that started the day before are clearly shown, as expected.

My specific scenario:
- Used 5:30 AM as the beginning of the new day (set a few days ago, not when the bug occurred)
- Started and ended a bunch of activities before midnight
- Started and ended a bunch of activities _after_ midnight
- Ran `hamster-cli list -3:00` and a few more variations like `hamster-cli list 23:15`, etc.,  during the time period 1AM-3:30AM on the same they when those "invisible" activities were recorded

![hamster-cli-after-midnight](https://cloud.githubusercontent.com/assets/983998/10415543/2fbdac56-6fc8-11e5-8b42-f81c52ae5b1f.png)

**Comment by losvald** [comment]
Interestingly, after changing the beginning of the day to midnight, `hamster-cli list` does show activities form either day, but `not from both`. If the intended behavior is indeed to show only a single day, then the former case is indeed a bug, because when the day starts after midnight, all activities before that date should be in the same "logical date" / group as those before midnight.

Here is the output after changing the beginning of the new day to midnight:

	losvald@t450:tmp$ date
	Sun Oct 11 03:37:36 EDT 2015
	losvald@t450:tmp$ hamster-cli list '-2:00'
	 Start -   End (Duration) | Activity@Category Tags
	--------------------------+------------------------
	 02:11 - 02:22 (   11min) | Another Act@Another Cat #SoleTag #TopCoder
	 02:48 - 02:51 (    2min) | FooBaz@PS 
	losvald@t450:tmp$ hamster-cli list '-4:00'
	 Start -   End (Duration) | Activity@Category Tags
	--------------------------+------------------------
	 23:40 - 23:42 (    1min) | HelloWorld@PS TopCoder 
	losvald@t450:tmp$ date
	Sun Oct 11 03:37:53 EDT 2015

**Comment by ederag** [comment]
The "midnight bug" has been fixed in v2.1.1.
Now activities between two end-of-day correctly belong to the same logical day.
