### ISSUE TITLE
Tracking settings don't save

### ISSUE THREAD

**Issue by lilHermit** [projecthamster/hamster#265]
I installed from source via a cloned repo 

```
./waf configure build --prefix=/usr/local
sudo ./waf install
```

and whatever I change in Tracking settings they live until I logout. They seem to persist when I kill the two services and reload Hamster.

Any tips to debugging this?

**Comment by ederag** [comment]
Thanks for the report.
With `lubuntu-18.10` and current master (d15e153a88552fc4a5388433f4334a105ac6f129),
following precisely [this procedure](https://github.com/projecthamster/hamster#building-and-installing)
with this additional step to [adapt](https://github.com/projecthamster/hamster/issues/221#issuecomment-462094920):
`sudo mv /usr/lib/python2.7/dist-packages/hamster/ /usr/lib/python3.6/dist-packages/`
the settings seem conserved.

Hopefully fixed then, but please ask here if it is not the case on your system.

**Comment by ederag** [comment]
Settings were not saved probably because gconf schemas were stored in `/usr/local/etc`,
due to `--prefix=/usr/local` and waf [gnu_dirs](https://waf.io/apidocs/tools/gnu_dirs.html) defaulting
`SYSCONFDIR` (host-specific configuration) to `PREFIX/etc`.
This is one aspect of issue #309.

**Comment by ederag** [comment]
Another source of non-persistent settings is a non-writable `~/.gconf/`. 
Normally,
```bash
> ls -l ~/.gconf/apps | grep hamster-time-tracker                                                                       
drwx------  2 username users  24 <date time> hamster-time-tracker
```
