### ISSUE TITLE
Activity crossing midnight is given negative duration

### ISSUE THREAD

**Issue by rrthomas** [projecthamster/hamster#266]
If I type e.g.

21:21 00:50 foo@bar

Then the "00:50" is correctly shown in the preview as being the next day, but the activity does not show up in the overview, and is given as having a negative duration in the database (checked with sqlitebrowser).

See #196.

**Comment by lambdafu** [comment]
It's even worse - if you change the time back to be after midnight, the whole activity shifts to the previous day.  And there seems to be no way to change the day.  Hamster was working perfectly fine, now it's utterly broken, but downgrading to 1.04 fixed it again for me.

**Comment by lambdafu** [comment]
Also, it is very easy to corrupt other entries when this happens, because overlapping regions are immediately truncated.  It is very destructive and there is no way to undo it.

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by ederag** [comment]
Thanks for the report.
This has been fixed in [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
