### ISSUE TITLE
CLI for new activity.

### ISSUE THREAD

**Issue by daniel-barrows** [projecthamster/hamster#268]
First, a disclaimier: I am running an old version of hamster:
- hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu1_all.deb
- hamster-indicator_0.1+037dd2e-0ubuntu2_all.deb

I wanted to add an entry to my usual startup script to popup the "New Activity" window. I am able to access this window by using the indicator, and selecting "New Activity". I have 3 hamster executables in my $PATH:
- hamster-cli
- hamster-indicator
- hamster-time-tracker

None of these seems to provide access to initialize this New Activity Window. Could you provide a CLI to do this? I suspect lots of people would like to show it on startup if they thought of it.

**Comment by ederag** [comment]
Good news. As shown by `src/hamster-cli --help`,
In master there is a `src/hamster-cli overview` command that opens the overview window.
Then `Ctrl-N` opens the "add activity" window.
Using arrows before `Ctrl-N` to select a previous activity allows to clone it.

So now it is only one more step than desired.

**Comment by daniel-barrows** [comment]
Well, I still think it's worth having a CLI interface for this, but I suppose an easy-to-remember key combination from the main window is okay.

**Comment by ederag** [comment]
It's actually almost possible. Please open a new issue. 
This one will be kept open with the `hamster-applet` label,
which means zero priority from me at least.

**Comment by daniel-barrows** [comment]
This feature was added in https://github.com/projecthamster/hamster/commit/88c9e6839c1b1a9f557f4e0b48ab5873f1c143b1#diff-aaeb1df16645c70d649ca07bf566ed66R160

Thanks!

**Comment by ederag** [comment]
Thanks for the feedback, and the link !
Let us keep it open, with the `hamster-applet` label,
which means that only the version 1 branch has the bug.

**Comment by ederag** [comment]
Closing, since this issue is thought to be solved in the development version.
(the meaning of the hamster-applet label has been [changed](https://github.com/projecthamster/hamster/issues/312#issuecomment-521266921))
Thanks for contributing to hamster improvement !
