### ISSUE TITLE
Readme.md: Missing dependency for Debian 8 Jessie

### ISSUE THREAD

**Issue by gkarsay** [projecthamster/hamster#269]
Hamster doesn't work without package python-gi-cairo on Debian 8 (Jessie). Tested version: Hamster 2.0-rc1, installed from source.

**Comment by kraiz** [comment]
Yeah, thanks for mentioning!

Installed rc1 from release deb file and had the same problem.

**Comment by ederag** [comment]
Thanks for the report. Fixed.
