### ISSUE TITLE
Re-introduce activity overview behaviour from 1.x to version 2+

### ISSUE THREAD

**Issue by Orbixx** [projecthamster/hamster#277]
My Hamster use case it to track time spent and report those times and tasks into time sheet software required by the company I work for.

In version 2, the tracking has seemingly gotten a bit worse. I can no longer see decimal values for the time spend on each bar, and the activities themselves are no longer showing, just the categories and the tags. I can also no longer select a single category, tag or task and have Hamster adjust the other bars to show related items.

I would love it if this was reintroduced, as the new Hamster otherwise looks much better, but version 2 destroys my use case.

**Comment by auipga** [comment]
+1
I'm still using v1 too

**Comment by olafhering** [comment]
+1

**Comment by helmo** [comment]
+1 for showing the sum of time spent on an activity in the overview window.

Additionally we could add an option to the command line 'list' operation, e.g. `--summary`

**Comment by mareg** [comment]
:+1:

**Comment by DevNiall** [comment]
:+1:

**Comment by helmo** [comment]
![hamster_overview_bar_indication](https://cloud.githubusercontent.com/assets/104120/14643235/e6568494-064d-11e6-8ee1-acc05bc08659.png)

Here's a screenshot to visualize the issue... Ubuntu 16.04, hamster master branch and the gnome shell extension loaded.

**Comment by helmo** [comment]
Not pretty, but it shows the time of each bar.

![hamster-windows-service_033](https://cloud.githubusercontent.com/assets/104120/15506018/2509c51e-21c6-11e6-8caf-00d5c3a6fe44.png)

**Comment by ederag** [comment]
The totals are displayed in the current master
(and already there in [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1)).
