### ISSUE TITLE
Pausing activity

### ISSUE THREAD

**Issue by ComputingFroggy** [projecthamster/hamster#279]
Hi,

I am sure I am missing something as the feature I am missing is fairly basic: I would like to be able to pause an activity while I have been interrupted (say by a phone call or for lunch) and to be able to resume the activity later on.

At the moment, the only way I've found to do this, is to stop the activity and to, later on, start a new activity and typing the same information again. If I could, at least, recall all the fields (including the description) with a single click that would work for me.

Cheers,
L@u

**Comment by DefteZ** [comment]
Hello L@u,
You can copy and start any (today) activity with the same description and tags by mouse double-clicking on it.
You even do not have to stop previous record.

**Comment by ComputingFroggy** [comment]
I don't understand: where do I double click on a previous activity ?

If it's on the week activity list, double cliking edit the activity registered: it does not copy it !

**Comment by DefteZ** [comment]
It works only in main window ("Time tracker")

**Comment by ComputingFroggy** [comment]
Great ! ! I installed the latest version with the PPA instead of the one from the Ubuntu repo and that works well ! ;
Cheers.

**Comment by satyanash** [comment]
I think this issue be closed now.

**Comment by Boltgolt** [comment]
I'd love a simple "restart last activity" option on the system tray dropdown

**Comment by ederag** [comment]
Should be solved when PR #372 is finished. Feedback would be welcome !
