### ISSUE TITLE
Activities with accent marks in name 

### ISSUE THREAD

**Issue by miguelcordero** [projecthamster/hamster#286]
If I create a activity with acute mark or accent mark in their name, like "Exposición", hamster doesn't permit save or modify their description. 
The Save button doesn't work when i type something in description box and window doesn't close. 
If I type in Title box, after the @,  button Save works and closes the window but not saves the new content. 

I run Debian 8.2, and i test with hamster_2.0-rc1-2_all.deb and building from source with master release also.

**Comment by ederag** [comment]
Thanks a lot.
This utf-8 issue has hopefully been fixed by the [python3 migration](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
