### ISSUE TITLE
hamster stop working after update from 1.04-5.fc23 to 2.0-0.2.rc1.fc23

### ISSUE THREAD

**Issue by hacrot3000** [projecthamster/hamster#293]
I got this problem on Fedora 23 - Gnome after update some package today. It was work well before update. 

The update log show:
>    Upgraded hamster-time-tracker-1.04-5.fc23.noarch                      (unknown)
 >   Upgrade                       2.0-0.2.rc1.fc23.noarch                 @updates

Run hamster command I got:

> [duongtc@duong-tc ~]$ hamster
> /usr/lib/python2.7/site-packages/hamster/lib/stuff.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk as gtk
> /usr/lib/python2.7/site-packages/hamster/lib/configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
>   from gi.repository import GConf as gconf
> Traceback (most recent call last):
>   File "/usr/bin/hamster", line 387, in <module>
>     hamster_client.overview()
>   File "/usr/bin/hamster", line 152, in overview
>     self._launch_window("overview")
>   File "/usr/bin/hamster", line 143, in _launch_window
>     getattr(server, window_name)()
>   File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
>     return self._proxy_method(*args, **keywords)
>   File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.159 was not provided by any .service files
> 

Run /usr/bin/hamster-service I got:

> /usr/lib/python2.7/site-packages/hamster/lib/stuff.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk as gtk
> /usr/lib/python2.7/site-packages/hamster/idle.py:24: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
>   from gi.repository import GConf as gconf
> hamster-service up
> Segmentation fault (core dumped)
> 

I downgrade hamster-time-tracker to 1.04-5.fc23 and it is back. I will now disable any update for hamster-time-tracker :)

**Comment by FelixSchwarz** [comment]
This is a problem with the Fedora version you're running. It was fixed in hamster git (#254). The underlying bug is Gnome's glib/gio ( https://bugzilla.gnome.org/show_bug.cgi?id=755721 ) and is likely to be fixed for Gnome 3.20.

Fedora just pushed an update (hamster-time-tracker-2.0-0.3.rc1.fc23 - the '0.3' here is important) which will fix the issue for you. However you still get hamster 2.0 which you might like (or not).

**Comment by sanjayankur31** [comment]
Thanks for pointing out the update @FelixSchwarz  - can probably close this issue @tbaugis @toupeira :)

Cheers!

**Comment by nathanaelmartel** [comment]
I got the same problem on an ubuntu 18.04 fresh install
