### ISSUE TITLE
Print or extract features

### ISSUE THREAD

**Issue by JonathanNEMRY** [projecthamster/hamster#294]
Hi!
Is there any features allowing to print time trackin or extract it?
If not, is it into the scope of the future improvements?

Thanks!

**Comment by FelixSchwarz** [comment]
I use "hamster export tsv" to get a plain-text tab separated list of activities and then process these items with shell tools (grep) and LibreOffice. Maybe that already solves your problem?

**Comment by JonathanNEMRY** [comment]
It could make the job. Where can I find this export tsv? I've read this one https://github.com/projecthamster/hamster/issues/193 but don't see save or export menu

**Comment by FelixSchwarz** [comment]
I'm using this directly on the command line: `hamster export tsv 2016-01-01 2016-01-31` to return all activities in January. Then often `| grep -i FooProject` to get just the logged time for "FooProject". Of course you can do all the regular shell stuff like `> outputfile.tsv`

**Comment by JonathanNEMRY** [comment]
@FelixSchwarz thank you for your answers! I close this issue
