### ISSUE TITLE
Task edit window not resizeable

### ISSUE THREAD

**Issue by lechndo** [projecthamster/hamster#295]
Hi hamster team,

first I want to say this app is great...

...but in the version currently coming with my Fedora 23 the task editing window is not resizeable and therefore the description widget is not displayed. (see 1st screenshot)
I fixed it for me by editing the corresponding ui file and provide it for you so you can easily integrate the changes if it is not already fixed. (see edit_activity.ui.txt)
I made the window resizeable and the description field expanding. See second screenshot for the result.

![edit_task_orig](https://cloud.githubusercontent.com/assets/11909747/13145004/26c29c8c-d64e-11e5-9f95-71b496ceb662.png)
![edit_task_resizeable](https://cloud.githubusercontent.com/assets/11909747/13145009/2f901f10-d64e-11e5-9b95-133c2e98afb4.png)
[edit_activity.ui.txt](https://github.com/projecthamster/hamster/files/136259/edit_activity.ui.txt)

**Comment by cislo78** [comment]
lechndo,
many thanks for sharing your solution. Very appreciated.
Here what i've done in detail (hope can help someone):
- downloaded file posted by lechndo
- back up original file with sudo cp /usr/share/hamster-time-tracker/edit_activity.ui /usr/share/hamster-time-tracker/edit_activity.bak
- copy downloaded file to right position without .txt extension: sudo cp /_downloaded _file_ _position_/edit_activity.ui.txt /usr/share/hamster-time-tracker/edit_activity.ui
Done.

**Comment by axelsimon** [comment]
To make it even more to the point, if this can help anyone:
- cd /usr/share/hamster-time-tracker
- sudo wget https://github.com/projecthamster/hamster/files/136259/edit_activity.ui.txt
- sudo cp edit_activity.ui edit_activity.ui.bak
- sudo cp edit_activity.ui.txt edit_activity.ui

**Comment by ederag** [comment]
Thank you all for your contributions (fix and tests) !
