### ISSUE TITLE
Hamster Time Resets Configuration on restart

### ISSUE THREAD

**Issue by amrnegm** [projecthamster/hamster#299]
When I set some configuration parameters like "Stop Tracking when computer becomes idle" or any other one, it resets on restart.
My Platform as follows:
- Ubuntu 15.10
- Gnome 3.18.2
- Hamster Plugin for Gnome.

**Comment by ederag** [comment]
Thanks for the report.
Looks like #265 ?
Please advocate here if I'm missing an important difference.
