### ISSUE TITLE
I made a side project : web-report-hamster

### ISSUE THREAD

**Issue by border0464111** [projecthamster/hamster#300]
Hi, this is just to report that I made this : 
border0464111/web-report-hamster

Have a good day.

**Comment by helmo** [comment]
Nice, 
clickable link: https://github.com/border0464111/web-report-hamster

Maybe the readme could list such related projects

**Comment by border0464111** [comment]
I have made a quick rewrite the controller and model in php  due to the fact that flask-hamster is currently broken and probably won’t get fix.

https://github.com/border0464111/php-report-hamster
