### ISSUE TITLE
Install and run in virtualenv

### ISSUE THREAD

**Issue by lmasikl** [projecthamster/hamster#315]
Hello!
I have Tracker instance in my system and wanted to contribute.
What should I do to do this?
I should uninstall it from system.
Fork repo and install Tracker in system.
Write some code update Tracker in system.
Create pull request.

Or I have possibility to install and run Tracker in virtualenv?

**Comment by ederag** [comment]
Thanks for your interest.
More informations in https://github.com/projecthamster/hamster/issues/233.
