### ISSUE TITLE
html report and non-ASCII characters

### ISSUE THREAD

**Issue by Chrescht** [projecthamster/hamster#317]
The html report file is not correctly showing the non-ASCII characters.
Examples:
vérification -> vÃ©rification 
à -> Ã

Installed version is 2.91.3 on Ubuntu 16.04.

**Comment by AnotherOneAckap** [comment]
It seems that I have this bug too.
When I use cyrillic symbols in activity descriptions and then try to save reports, symbols becomes corrupted like "Ð°Ð²Ð³ 04, 2017", month names too. They looks like **double utf-8 encoded**, and I thought problem is in template, but data are exported in template `/usr/share/hamster-applet/report_template.html` just like `$facts`, that where all troubles happen.

I use Time Tracker 2.91.3 on Ubuntu 16.04.3 LTS with Python 2.7.11.

**Comment by ederag** [comment]
Thanks for the report.
This utf-8 issue has hopefully been fixed by the [python3 migration](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
