### ISSUE TITLE
Resize of the update activity window (Ubuntu)

### ISSUE THREAD

**Issue by efender** [projecthamster/hamster#318]
Is it possible to add a resize of the update activity window in Ubuntu?
In particular, resize the field "Description".

![2016-05-06 e0ddedcf](https://cloud.githubusercontent.com/assets/6908417/15064821/b9cd5aaa-1369-11e6-95f6-c23be1b17029.png)

**Comment by ederag** [comment]
Close to https://github.com/projecthamster/hamster/issues/295.
