### ISSUE TITLE
ImportError: No module named xdg.BaseDirectory

### ISSUE THREAD

**Issue by nmpribeiro** [projecthamster/hamster#319]
So... installed it, and when I try to fire it up "$ hamster":

```
$ hamster 
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
  File "/usr/lib/python2.7/site-packages/hamster/reports.py", line 32, in <module>
    from hamster.lib.configuration import runtime
  File "/usr/lib/python2.7/site-packages/hamster/lib/configuration.py", line 27, in <module>
    from xdg.BaseDirectory import xdg_data_home
ImportError: No module named xdg.BaseDirectory
```

**Comment by dilom** [comment]
I have the same problem.

**Comment by smu** [comment]
Same here.

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by ederag** [comment]
`python-xdg` was needed. This has been added to the [dependencies](https://github.com/projecthamster/hamster#dependencies) instructions.

**Comment by avezou** [comment]
I still have the same problem on Ubuntu 22.04 in 2022. What worked for me was copying BaseDirectoty.py from /usr/lib/python3/dist-packages/xdg/ to ~/.local/lib/python3.10/site-packages/xdg
