### ISSUE TITLE
activities from 12 midnight up to ~5 am are grouped into previous day

### ISSUE THREAD

**Issue by emillosanti** [projecthamster/hamster#325]
activities that are incurred from 12 midnight until after 5 am are included into previous day
i.e.
  04:00 - 04:30 am on Tuesday morning
in overview is included with Mondays activities

**Comment by border0464111** [comment]
Is it UTC-5 where you live ?

**Comment by emillosanti** [comment]
I'm at UTC+8

**Comment by Bifros7** [comment]
![image](https://cloud.githubusercontent.com/assets/13536271/16296072/acf1b52e-392a-11e6-852e-f699fcc7d2ec.png)
Is this what you're looking for? @emillosanti

**Comment by emillosanti** [comment]
sorry for the inconvenience.
tyvm @Bifros7
