### ISSUE TITLE
How to delete a tag?

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster#328]
Dear all, 

Thank you so much for your work on this excellent time-tracker for Linux. 

I love the integration in Ubuntu Unity. :smiley: 

A quick question:

I couldn't find any way to delete an existing tag. Is this feature being implemented and I have just not found the right way how?

Thankfully,

~Robert

**Comment by elbenfreund** [comment]
Thank you for your feedback Robert. As far as I am aware there is no such capability in the frontend right now. You would have to edit the sqlite table directly. Please feel free to open a feature request ticket though.

Also, please note that project hamster is undergoing some major changes right now and bugs within the current codebase are unlikely to be fixed. Feature requests however will be revisited once we are ready to launch out rewritten codebase and anything still relevant will still be considered.

**Comment by orschiro** [comment]
Dear @elbenfreund,

Thank you very much for your message! Where can I follow-up on these new developments?

Warmly,

~Robert

**Comment by elbenfreund** [comment]
The relevant repositories housing the new codebase are ``hamster-lib/dbus/cli/gtk``. Most of them have already made significant progress but are not yet prime time ready. If you feel like getting involved with project hamster youself, (code, documentation, artwork. ...) do not hesitate to let us know :)
For more general information and a general meta perspective on project hamsters development i would point you to http://projecthamster.org, which is rather low traffic.

Thanks for your interest and all the best.

**Comment by orschiro** [comment]
Dear @elbenfreund, 

I just read about Project Hamster's reboot on the website and would like to help with:

- Documentation
- Translation
- Communication

Let me know if you need any of these aspects at the current stage!

Warmly,

~Robert

**Comment by elbenfreund** [comment]
Thats great news!
if you are interested, please join the [development mailinglist](http://lists.projecthamster.org/listinfo.cgi/hamster-dev-projecthamster.org) to discuss particular contributions.

Welcome aboard.

**Comment by orschiro** [comment]
Thank you, Eric!

I just joined the mailing list and will look forward to future conversations. 

~Robert

**Comment by orschiro** [comment]
Hello @elbenfreund , 

I know this is legacy but I do have one more question. 

Until the new GTK applet is fully functional, I need to rely on this old version for my day to day work. 

However, I frequently enter the wrong tag by accident and thus would like to delete them to avoid any further mistakes. 

Could you give me a brief instruction how to delete a tag through the SQLite interface?

Thankfully,

~Robert

**Comment by elbenfreund** [comment]
Does the reference to ``SQLite Manager`` in #238 suffice or do you need help with manipulating the database?

**Comment by orschiro** [comment]
That should be sufficient, thank you Eric!

Can you just quickly point me to the database location?

I expected it to be under `.config/hamster` which, however, doesn't exist. 

~Robert

**Comment by orschiro** [comment]
Eventually found it under `.local/share`. 

Problem solved, thank you!

![image](https://cloud.githubusercontent.com/assets/170947/17364488/b84212d6-5980-11e6-8aa0-1ade78ca3474.png)
