### ISSUE TITLE
How to stop current activity?

### ISSUE THREAD

**Issue by haunted2** [projecthamster/hamster#333]
Hello. Is there a way to stop the current activity without switching to a new one? Hamster keeps traking some activity until the pc is inactive for a certain time or it is halted, according to settings. I would like to be able to stop it even while i'm using the pc.
Thanks.

**Comment by fralix** [comment]
Switched from 1.93 and this was implemented there? Why got it removed? I can't even see a way to switch my activity, the new frontend is terrible!

**Comment by ruedigerkupper** [comment]
Confirming. Stop activity is only available from the shell extension. You can't stop an activity from hamster-applet. I wonder, why no-one else reports this? You have to stop activities all the time...

**Comment by ederag** [comment]
Indeed, but
closing as duplicate of #310 
(the screenshot there showed the old interface, but it is definitely about version 2)
