### ISSUE TITLE
integration of hamster-lib with org-mode?

### ISSUE THREAD

**Issue by trenkert** [projecthamster/hamster#334]
org-mode (http://orgmode.org) has great time tracking abilities (among other things). Sadly, it isn't really integrated into GNOME. would it be possible to have hamster track the org-agenda?

**Comment by elbenfreund** [comment]
Hi there :)
Whilst I know several people using orgmode very happily I am not of them and as such can not really guess what would be needed to make both play nice together. This is not helped by me belonging to the church of vi(m). ;)
What I can say however is that it is a declared goal of project hamster to provide easy interfaces to whatever other timetracking is out there as possible. So this is *in general* something we find very interesting.
Right now however, we are trying to solidify / refactor the main codebase and already existing auxiliary tools, so I doubt there will be any work by the core team on this in the foreseeable future.

You may want to check out [hamster-bridge](https://github.com/kraiz/hamster-bridge) which listens for hansters dbus signals and tries to integrate hamster with various other timetrackers. Maybe this is a viable road for orgmode too.

If you wish to continue this discussion I would kindly ask of you to reopen this issue in the ``hamster-lib``
repository as this one (``hamster``) is for the soon to be deprecated *legacy hamster*.

Hope this first feedback gave you some pointers and please let us know I you find out more on that matter!

Eric
