### ISSUE TITLE
Unable to create report

### ISSUE THREAD

**Issue by mateusz-holysz** [projecthamster/hamster#335]
Recently I have installed master build of hamster. Software reads my db, but it is not able to export any report. It creates null file. Exported file has 0 bytes. Please advice. Hamster is great. My OS Ubuntu 16.04 I tried to return to previous stable installation from ubuntu repository. It was not possible hamster does not start.

Finally I have returned to stable installation. This thread helped
https://github.com/projecthamster/hamster/issues/165

**Comment by ederag** [comment]
Thanks for the report. Should be fixed with PR #375.
