### ISSUE TITLE
Gnome Shell Extension won't load with Wayland (Fedora 24)

### ISSUE THREAD

**Issue by pmk1c** [projecthamster/hamster#337]
I'm trying to load the Hamster Gnome Shell Extension on Wayland, but I get the following error: 

> Gjs-Message: JS LOG: Extension "hamster@projecthamster.wordpress.com" had error: Gio.IOErrorEnum: Fehler beim Aufruf von StartServiceByName für org.gnome.Hamster: Zeitüberschreitung wurde erreicht

The german part translates to:

> Error calling StartServiceByName for org.gnome.Hamster: Timeout reached

**Comment by elbenfreund** [comment]
Hi there.
Please report issues to the appropiate repository. In your case ``shell-extension`` as this is clearly the right place to go.
On a sidenote, this may be related to [an existing issue](https://github.com/projecthamster/shell-extension/issues/115).

**Comment by pmk1c** [comment]
Oh I'm sorry. I wondered why nobody had reported this here -.-
