### ISSUE TITLE
Hamster not starting. Windows port.

### ISSUE THREAD

**Issue by octaviordz** [projecthamster/hamster#350]
Several years ago around 2012 maybe, I found out about tracker and I been using it since then.
Now I'm a windows, back then I found a installer someone posted online and that is the one I been using since then without any problems.
I at some point I downloaded the source code and found out there was a branch for the windows port but even back then it was no longer being updated. Haven't check if that is changed at all.

Now as of today hamster time tracker just stopped working on my work computer, no error is shown.
I tried to open it in the windows console to see if there was any error shown in the console but nothing.
I already uninstalled it and reinstalled it and still the same.

I'm hoping someone can  point out some way to track the issue down, any help is appreciated, thanks

I attach the installer I use in a zip file.
[hamster-setup.zip](https://github.com/projecthamster/hamster/files/1363532/hamster-setup.zip)

**Comment by octaviordz** [comment]
In case this helps someone else. The issue was with hasmter.ini [1] for what ever reason it got corrupted. I deleted the file and let hamster recreate it.

1) %AppData%\hamster-applet\hamster.ini

**Comment by elbenfreund** [comment]
Glad to hear you solved your problem! :)
