### ISSUE TITLE
Crashes after switching to Turkish!

### ISSUE THREAD

**Issue by mbnoimi** [projecthamster/hamster#351]
Hi,

After switching my PC language's interface from English to Turkish hamster crashes!

```
 $ /usr/bin/hamster-time-tracker
ERROR:dbus.proxies:Introspect error on :1.241:/org/gnome/Hamster: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/usr/bin/hamster-time-tracker", line 602, in <module>
    app = ProjectHamster()
  File "/usr/bin/hamster-time-tracker", line 78, in __init__
    self.create_hamster_window()
  File "/usr/bin/hamster-time-tracker", line 152, in create_hamster_window
    self.new_name = widgets.ActivityEntry()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 103, in __init__
    self.populate_suggestions()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 234, in populate_suggestions
    self.activities = runtime.storage.get_activities(fact.activity)
  File "/usr/lib/python2.7/dist-packages/hamster/client.py", line 136, in get_activities
    return self._to_dict(('name', 'category'), self.conn.GetActivities(search))
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.241 was not provided by any .service files
$ 
```
- I use Linux Mint 18.2 x64
- log of locale
```
$ locale
LANG=tr_TR.UTF-8
LANGUAGE=tr_TR
LC_CTYPE="tr_TR.UTF-8"
LC_NUMERIC=tr_TR.UTF-8
LC_TIME=tr_TR.UTF-8
LC_COLLATE="tr_TR.UTF-8"
LC_MONETARY=tr_TR.UTF-8
LC_MESSAGES="tr_TR.UTF-8"
LC_PAPER=tr_TR.UTF-8
LC_NAME=tr_TR.UTF-8
LC_ADDRESS=tr_TR.UTF-8
LC_TELEPHONE=tr_TR.UTF-8
LC_MEASUREMENT=tr_TR.UTF-8
LC_IDENTIFICATION=tr_TR.UTF-8
LC_ALL=
```

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated. At a glance, it looks that your underlying dbus service ``hamster-service`` is no longer running.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by mbnoimi** [comment]
@elbenfreund Thanks.

Do you've a road map for upcoming release? Your old road map mentioned ``dbus`` issue but without a real date. Because I'm unable to use hamster at all because of this bug (I tried to revert back to English interface but I still get same error)

**Comment by elbenfreund** [comment]
Depending on your use case you could try ``hamster-gtk`` 's ``develop`` branch. Please be advised however that there is currently no support for migrating your old data (which should not be overwritten either though. But still, better back up!).

**Comment by mbnoimi** [comment]
I'm really sad for Project Hamster because it's the most reliable open source project for time tracking but unfortunately it's too early to rely on ``hamster-gtk`` so I'm forced to leave it after years of using it 😭 😭 😭

I hoped to get a help for fixing this issue.

**Comment by elbenfreund** [comment]
I am sorry to hear that. Are you missing specific features in ``hamster-gtk`` that make it a no-go or is it its early development stage in general that rules it out as an alternative?

**Comment by mbnoimi** [comment]
> Are you missing specific features in hamster-gtk that make it a no-go or is it its early development stage in general that rules it out as an alternative?

I didn't install it at all because there is no already built binaries for ubuntu (I'm too lazy to build it from source code)

**Comment by elbenfreund** [comment]
I see. Thanks for getting back to us and all the best on your future endeavours.
