### ISSUE TITLE
Package hamster_2.0-rc1-2_all.deb on Ubuntu 17.10 raises DBusException

### ISSUE THREAD

**Issue by thekswenson** [projecthamster/hamster#354]
I installed the package hamster_2.0-rc1-2_all.deb on Ubuntu 17.10 and got the following error:

> => hamster 
> /usr/lib/python2.7/dist-packages/hamster/lib/stuff.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk as gtk
> /usr/lib/python2.7/dist-packages/hamster/lib/configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
>   from gi.repository import GConf as gconf
> Traceback (most recent call last):
>   File "/usr/bin/hamster", line 387, in <module>
>     hamster_client.overview()
>   File "/usr/bin/hamster", line 152, in overview
>     self._launch_window("overview")
>   File "/usr/bin/hamster", line 143, in _launch_window
>     getattr(server, window_name)()
>   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
>     return self._proxy_method(*args, **keywords)
>   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.351 was not provided by any .service files

**Comment by LRGV** [comment]
the same problem compiling in Debian Stretch 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

thanks in advanced
R

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by ederag** [comment]
Thanks for the report !
This is hopefully fixed in [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
