### ISSUE TITLE
Tags box in Preferences->Categories and Tags tab is 0 px high

### ISSUE THREAD

**Issue by soylentdeen** [projecthamster/hamster#358]
When attempting to edit some of my Tags using the box in the Categories and Tags tab in the Preference window, the box which displays the tags has a height of ~1-2 pixels. I am still able to select the tabs, but have no idea what I am doing to them (as the window is not large enough).

I'm on Ubuntu 16.04 LTS and have Time Tracker 2.91.3.
![hamsterbug](https://user-images.githubusercontent.com/210195/41353858-bc0a33f8-6f1d-11e8-854c-b186ccd8b08c.PNG)

Is this a bug which is fixed in later version?

**Comment by jeisoncp** [comment]
I have the same problem.

**Comment by ederag** [comment]
Thanks for the report.
Yes, this is fixed in current version ([v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1))

**Comment by ederag** [comment]
Closing, since this issue is thought to be solved in the development version.
Thanks for contributing to hamster improvement !
