### ISSUE TITLE
plugin hamster stop working after upgrading from gnome 3.22 to 3.28

### ISSUE THREAD

**Issue by karolszk** [projecthamster/hamster#360]
Hi!

I've just upgaded my debian stretch installation to buster (testing) and plugin got error:

SyntaxError: redeclaration of let renderer

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

how to fix it?

Regards, Karol

**Comment by GeraldJansen** [comment]
A recent working version of the shell extension was reported [here](https://github.com/projecthamster/hamster/issues/356#issuecomment-525604739).

At any rate this looks like an issue for the Gnome [shell extension](https://github.com/projecthamster/hamster-shell-extension) so I guess the issue should be closed here and re-opened there if still relevant.
