### ISSUE TITLE
debian/RPM dependencies still for python2

### ISSUE THREAD

**Issue by ederag** [projecthamster/hamster#369]
Since the python3 migration, the [README](https://github.com/projecthamster/hamster/edit/master/README.md) should be updated.

**Comment by GeraldJansen** [comment]
I didn't feel confident enough to update the README so I created a temporary page [here](https://github.com/GeraldJansen/hamster/wiki/Hamster-2.x-on-Xubuntu-18.04). I think the difference boils down to installing the python3 versions of some packages (python3-gconf python3-xdg python3-dbus python3-gi-cairo) and using the python3 multi-version directory /usr/lib/python3/dist-packages.

**Comment by sliwowitz** [comment]
On Ubuntu 19.04, there is no python-gconf (or python3-gconf) package in the repos anymore. I was able to run hamster with this combination:
`sudo apt-get install gettext intltool gconf2 gir1.2-gconf-2.0 python3-gi-cairo python3-dbus python3-xdg`

Just a note - I'm not sure if that would work for clean installs as I do a lot of python development, and might have some leftover packages lurking somewhere among all the python paths.

**Comment by brainwane** [comment]
I followed @GeraldJansen's instructions on Debian buster just now and had a fairly good experience; I think it's running (including GUI) now.

**Comment by ederag** [comment]
@brainwane Thanks for the feedback.

A link to the wiki page is planned  to be added to the README then (PR #420).

**Comment by GeraldJansen** [comment]
Instructions moved to https://github.com/projecthamster/hamster/wiki/Hamster-2.x-on-Xubuntu-18.04.

**Comment by ederag** [comment]
PR #421 has been merged, with updated dependencies in the README.
Closing, thanks for the feedback !
