### ISSUE TITLE
html report shows no daily items

### ISSUE THREAD

**Issue by mabgh** [projecthamster/hamster#374]
```
Gesamt nach Tag
Unterscheiden: Tätigkeiten Kategorien Schlagworte
31.Dez.2018	0
01.Jan.2019	0
02.Jan.2019	0
```

gui shows items correctly.
Missing items are caused by `date_facts.append([str_date, by_date.get(date, [])])` (line 297 in 
reports.py.) where var `date` is `datetime`, but key of `by_date` is date.
Replacing `while date <= self.end_date:` (line 291 of reports.py) with
```python
        date = dt.date(date.year, date.month, date.day)  
        edate = self.end_date 
        edate = dt.date(edate.year, edate.month, edate.day) 
        while date <= edate: 
```
works with `hamster-cli`, but a report generated with the gui is thereby not changed.

**Comment by ederag** [comment]
Thanks for the report, and for searching a solution.
Hope you do not mind I edited it to improve its readability, using back-quotes to markup code.
Would you please try again with the branch given in PR #372 ?
With it HTML reports looks fine here.
Please ask here if you need guidance for the process.

**Comment by mabgh** [comment]
Am Sonntag, 6. Januar 2019, 22:35:43 CET schrieb ederag:
> Thanks for the report, and for searching a solution.
> Hope you do not mind I edited it to improve its readability, using
> back-quotes to markup code. Would you please try again with the branch
> given in PR #372 ?
> With it HTML reports looks fine here.
> Please ask here if you need guidance for the process.

Assuming PR #372 is latest commit from 2019-01-02 22:22:32.
With this version the problem persists both with gui and cli.

**Comment by ederag** [comment]
In the PR commits are given in reverse order with respect to e.g. gitk; please try d0739ae.
The gui should work (just tested again).
Side note: to indicate a commit, you may simply paste the number in your message;
github will create a link automatically.

**Comment by mabgh** [comment]
Still confronted with same problem, both gui and cli.
`  print('>> ', date , ' # ', by_date.get(date, []))
   print(' > ', dt.date( date.year, date.month, date.day) , ' # ', by_date.get(dt.date( date.year, date.month, date.day#`
(not executed with gui) shows 
_>>  2019-01-01 00:00:00  #  []_
_ >  2019-01-01  #  [{'id': 3515, 'activity': 'misc', 'category': 'admin', 'description': '', 'tags': [], 'date': 1546300800, 'start_time': 1546369200, 'end_time': 1546377000, 'delta': 7800.0}, {'id': 3516, 'activity': 'admin', 'category': 'it', 'description': '', 't_
git show-branch is
_! [master] Merge pull request #371 from ederag/fix_fact_str
 * [report] change Fact.delta to a property
--
 * [report] change Fact.delta to a property
 * [report^] use Fact instead of index argument for set_current_fact
 * [report~2] do not set a current fact by default
 * [report~3] compare Facts, based on their id field
 * [report~4] start a clone of the selected activity upon clicking "add"
 * [report~5] create Fact.copy()
 * [report~6] remove fact_date argument
 * [report~7] toggle fact selection on mouse click
 * [report~8] update self.hover_day before using it
 * [report~9] remove unused blank_day
-- [master] Merge pull request #371 from ederag/fix_fact_str
_
so I am probably using the version you requested.

**Comment by mabgh** [comment]
additional info: csv and ical reports contain only header, xml is void

**Comment by ederag** [comment]
It seems that your output is messed up, probably by the email process ?
Using the github interface instead of email is advisable.
For instance there is a preview.

As for the development version, please paste the output of
`git describe --abbrev=40 --always --dirty=+`
(found there: https://stackoverflow.com/a/49736799/3565696)

**Comment by mabgh** [comment]
git describe is 
d0739ae10df5602663e92dd0bb06783e61570fbc

**Comment by mabgh** [comment]
I have to correct me.
I found no differences in the schemas of the newly created db and the old one, but detected
some strange inconsistencies in the old db.
So I dumped the important tables of the old db and loaded them into the new one. The new one
is working fine, including reports.
So I have to say sorry for the noise based on a purely local problem.

**Comment by ederag** [comment]
Good. Thanks for having investigated further !
