### ISSUE TITLE
Wish: Add Support for Budgie

### ISSUE THREAD

**Issue by sixtyfive** [projecthamster/hamster#377]
Hamster is the greatest way of tracking time, ever. It would be awesome if it was available not only for GNOME, but also for all the other big Linux desktop environments. I'm using Budgie, so that's what I'll wish for with this ticket.

Not sure how difficult or easy this is from a Hamster or from a Budgie perspective, but I did find [an example](https://github.com/solus-project/budgie-desktop-examples/tree/master/python_project) and [the sources to Budgie's own applets](https://github.com/solus-project/budgie-desktop/tree/master/src/applets) by googling, as well as [someone asking how to write one and receiving an answer](https://askubuntu.com/questions/886327/how-do-i-write-an-indicator-for-budgie-desktop) and [the sources of what seems like a thirdparty-applet](https://github.com/UbuntuBudgie/budgie-indicator-applet).

Perhaps you'll consider this as an enhancement at some point :-)

**Comment by ederag** [comment]
Thanks for your interest with `hamster`, and for the research.
The `hamster` overview works just fine on any desktop (I'm using `kde` for instance),
despite the "GNOME time tracker" title.
Desktop integration is another thing, and there are very specific tweak for each desktop
(for instance `kde` uses "activities" in addition to workspaces),
and that is probably why desktop integration has been moved to other repos.
Budgie is currently using `gnome`, so the [hamster-shell-extension](https://github.com/projecthamster/hamster-shell-extension) might just work. That would be a starting point anyway.
Closing, but feel free to advertise here your progress.
