### ISSUE TITLE
Failure on special case of overlapping activities

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#409]
Hamster fails when inserting a new activity that spans the start time of an ongoing activity. In grafical mode the "Add earlier activity" window does not respond when you try to save the activity. In development mode:
```
[src]$ ./hamster-cli list
Start | End | Duration | Activity | Category
-----------------------------------------------
08:36 |     | 0h 5min  | xxx      | Unsorted
-----------------------------------------------

[src]$ ./hamster-cli track yyy 08:30 08:40
Traceback (most recent call last):
  File "./hamster-cli", line 414, in <module>
  ...
  File "/d/gj/hamster/src/hamster/storage/db.py", line 483, in __solve_overlaps
    if start_time < fact["start_time"] and end_time > fact["end_time"]:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'
```

**Comment by ederag** [comment]
This is a particular case, related to #396. Interesting, thanks !

**Comment by GeraldJansen** [comment]
I re-invented the wheel :-( See:
https://github.com/gsobczyk/hamster/pull/34/commits/c9d1332329974ecc3f1fee50489d208f5308d2a6

It seems a lot of good work was done in that fork.
