### ISSUE TITLE
ESC should not always close overview window

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#411]
When the overview window is opened by `hamster[-cli] [overview]&`, the ESCape key should not close the overview window and thus the hamster program. That behaviour is fine if the window was opened from some other app, say hamster-shell-extension, but not when it is the main application.

**Comment by ederag** [comment]
Agreed.
I guess you have already seen the subtlety, but to anyone else:
The current behavior is fine also when overview is launched from the command-line without the `&`.

Is it possible to know whether a python code runs detached ?

**Comment by GeraldJansen** [comment]
> Is it possible to know whether a python code runs detached ?
I was thinking about something simple like 
`     hamster_client = HamsterClient()
      hamster_client.from_cli = True`
in src/hamster-cli, i.e. an attribute which is only set if launched directly from hamster-cli. 

Haven't thought much about it and it is a low priority item.

**Comment by GeraldJansen** [comment]
Actually I've come to like the behaviour so I am closing this.
