### ISSUE TITLE
Incorrect highlighting of multiline descriptions

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#413]
Multiline descriptions (with embedded newlines) are not properly handled in the overview window. As shown in the screenshots below, when selecting tasks with the up/down arrows, the first task gets highlighted with the size of the second task and vice-versa. The selection of tasks by clicking on them is also messed up because of incorrect height calculations. This may be related to #274 and #412. 
(For me this is low priority because I don't personally use descriptions, but I thought it worthwhile  to document the issue anyway.)

![Screenshot_2019-05-11_16-59-14](https://user-images.githubusercontent.com/31414956/57571959-fd56c180-7414-11e9-8a16-a6ffec196b94.png)

![Screenshot_2019-05-11_16-57-55](https://user-images.githubusercontent.com/31414956/57571968-1bbcbd00-7415-11e9-96a5-a188ec99d939.png)

**Comment by ederag** [comment]
Good observation, thanks ! I'm on it.

**Comment by ederag** [comment]
Should be fixed by PR #414
