### ISSUE TITLE
Website is down -- website project looks abandoned?

### ISSUE THREAD

**Issue by spiraldancing** [projecthamster/hamster#422]
Hi guys.  Sorry, I know this is the wrong repo, but the web-repo does not look like it's being maintained, and the entire projecthamster ... uhh ... project points to the same (down) website.

Not sure, but by the Internet Archive and WHOIS info, it looks like it might have been down for awhile now.  I sent an email to "contact@projecthamster.org" ... it didn't bounce.

**Comment by GeraldJansen** [comment]
http://projecthamster.org/ ?  Looks up to me. But yes the rewrite project is stalled and that makes it look like the whole Hamster project is abandoned. It is a rather sad state of affairs, given that good work is being done to revive the hamster2.x line of development (i.e. legacy + gtk3 + python3).

**Comment by spiraldancing** [comment]
Oh, hey ... my bad ... sort of.  https://projecthamster.org/ is down.  I'm running HTTPS Everywhere plug-in in my browser.  Usually, on unencrypted sites, that plug-in throws a warning re-direct to the insecure version ... but in this case, I just get a Dreamhost "site doesn't exist" page.

**Comment by ederag** [comment]
Confirmed, thanks for the report.
The  https://projecthamster.org/ site issues can be found there:
https://github.com/projecthamster/hamster-website/issues
It would be good to have someone with the required knowledge to handle this site.
