### ISSUE TITLE
location error in waf (/us/ -> /usr/)

### ISSUE THREAD

**Issue by Oros42** [projecthamster/hamster#425]
Hello
With the master of today, when I run ```./waf install```, I got this :
```
Waf: Entering directory `/home/****/hamster-master/build'
* installing src/hamster-service as /us/lib/hamster-time-tracker/hamster-service
* installing src/hamster-windows-service as /us/lib/hamster-time-tracker/hamster-windows-service
* installing src/hamster-cli as /us/bin/hamster
* installing src/hamster.bash as /us/share/bash-completion/completion/hamster.bash
[...]
```
I think, you forgot the ```r``` of ```/usr/```.

**Comment by ederag** [comment]
Thanks for the report.
Please follow closely the instructions (in particular the `--prefix=/usr` part).
Otherwise you might end up with other issues such as #309.
The installation process is being worked on in #421.
