### ISSUE TITLE
Inconsistent handling of dates and times

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#428]
There are a number of places where dates and/or times are not handled consistently in current hamster. In part that is due to separate date-time parsing in hamster-cli.py and in lib.parse_fact() . These inconsistencies are confusing at best and in the case of rounding or not rounding times to nearest minute they can lead to different time totals reported by different versions of hamster (eg. #76).

Issues:
1) command line expects yyyy-mm-dd whereas edit_activity window expects dd-mm-yyyy
2) command line help says times can be specifed as hh:mm:ss but the seconds are truncated to 0 when using hamster[-cli] start/stop
3) starting/stopping a new activity from the GUI results in timestamps accurate to seconds, but 
 any subsequently edits result in the seconds being set to 0. 

Concerning the date format, the simplest solution would be to use `DATE_FMT = '%Y-%m-%d'` in lib.parse_fact to be consistent with the format used in hamster-cli, both for input and for listings and data export.
Concerning truncating timestamps to minute accuracy, I would be in favour of doing this consistently throughout hamster. Another possibility would be to offer a user preference to use either minute or second accuracy, and then apply that preference consistently throughout the application.

**Comment by ederag** [comment]
The `DATE_FMT = "%d-%m-%Y"` centralization introduced in d8c421abad77b191a274018b7b23e104a6486daa 
was keeping the existing date format in this file.
I'm all in favor to change to DATE_FMT = '%Y-%m-%d' (the ISO format),
all the more since it is consistent with command-line usage.

By the way, the command-line should use the `lib.*`  machinery;
not very difficult, but that would be a lot of work to test => not just before a release.

About rounding, maybe replacing `now` with a rounded value would be enough to solve point 3,
but that would require more thoughts.

**Comment by GeraldJansen** [comment]
I will work on this. Also looking at  [this](https://github.com/gsobczyk/hamster/commit/bd5fd6c1453a4aeb67119678a044658de4615912).

**Comment by GeraldJansen** [comment]
> About rounding time in python: https://stackoverflow.com/q/3463930/3565696

I believe truncating times to the minute by setting second=0 and microsecond=0 will be more consistent with current behaviour in some parts of the code and less problematic than rounding times to the nearest minute. For example, rounding could more frequently cause loss of a minute when manually stopping a task and starting a new one and rounding could create a timestamp in the future which could potentially be a problem (not sure though).

**Comment by ederag** [comment]
OK, I'd prefer nearest (twice better accuracy for the same sampling interval),
and provided that all comparisons are made on rounded values, it should be safe,
but let's truncate for now, in function probably located in `stuff.py`,
and leave room for experiments later.

**Comment by ederag** [comment]
Fixed by @GeraldJansen in PR #429, thanks !
