### ISSUE TITLE
date/time entry consistency

### ISSUE THREAD

**Issue by ederag** [projecthamster/hamster#438]
1) When `date` and `time` can be given explicitly together, e.g. `2019-09-01 02:00`,
they should be local time (the same as on the desktop wall clock),
as in `hamster-cli`.
This is seems to make more sense when entering both start and end datetimes:
`2019-09-01 04:00 - 2019-09-01 07:00`

2) When a day is selected separately, as with the gui timeline arrows in `activity_entry`,
then it means "hamster day" (that by default starts at 05:00).
This way the activity will appear in exactly this selected day when displayed
by the overview, `hamster list`, `hamster search`, ...

3) When only `time` is entered, the default date should be `hamster_today`.
Indeed, entering `23.50` half an hour later refers most probably to the current hamster day.
(using today would be very inconvenient here, think of entering `23.50 - 00.20`...).

4) Facts overlapping the hamster day start time (05:00 by default) are tricky.
e.g. entering `04:00 - 07:00` on 2019-09-01 at 07:30 would result in a
`2019-09-02  04:00 - 2019-09-01 07:00`, hence with a negative duration.
This has been solved for the gui in PR #437 by incrementing the end date 
(more secure than decrementing the start date) in case of negative duration.
A warning and a means to check and correct entry was given.
For command line this is a bit trickier. 
Just error on negative durations and require user to give full datetime information ?

**Comment by GeraldJansen** [comment]
It would be great if the same fact entry and parsing rules could be used for command line entry, the edit_activity window and the hamster-shell-extension:
`[yyyy-mm-dd]  [HH[:|.]MM]  [HH[:|.]MM] activity@category, description #tag1 #tag2 ...`
OR
`[yyyy-mm-dd]  [-nnn] [-nnn] activity@category, description #tag1 #tag2 ...`

In the first form, specifying end HH:MM lower than start HH:MM indicates a time on the next day. The maximum duration of an activity specified in this way would be limited to 23h59m.

**Comment by ederag** [comment]
To be clear, my point 1 was to replace the current syntax with
```
[yyyy-mm-dd] [HH[:|.]MM] [yyyy-mm-dd] [HH[:|.]MM] activity@category, description #tag1 #tag2 ...
```
The change would be major since the first date would not be the hamster day of the activity any longer.
Both `[yyyy-mm-dd] [HH[:|.]MM]` are datetimes, in local time.
IMO, there is no way to handle safely activities overlapping the hamster day start with the current syntax.
It just looks [too dangerous](https://github.com/projecthamster/hamster/issues/419#issuecomment-526947600).
Negative durations would be treated as errors.

**Comment by GeraldJansen** [comment]
Sounds good to me. I have tried to interpret and elaborate a bit on your intentions on this [wiki page](https://github.com/projecthamster/hamster/wiki/Entering-activities). Please feel free to edit and clarify as you see fit. Maybe it could become an "official" technical documentation page ...

**Comment by ederag** [comment]
Wiki page [Updated](https://github.com/projecthamster/hamster/wiki/Entering-activities/_compare/16af411bd553d85094a7807ece2def3dcc45feef...873c6479944eb680fc7295054a7574bc158d1e52); thanks for forcing me to think again and clarify. 
I'm more and more convinced that heuristics around negative durations are fragile 
(always some nasty corner cases), 
and that a clear hopefully simple rule is better (easier to understand, remember, and work around). 
If any of the changes reason is not clear, please ask here.
This document is interesting for the discussion, and potentially for documentation,
although there is some redundancy with the help pages.

`start_time` and `end_time` are somewhat confusing for someone knowing the code internals
(they are `datetime`, not mere `time`), and felt somewhat disturbing in the discussion, in general.
It might be the right time to change these attributes to `start` and `end`. Any objections ?

**Comment by GeraldJansen** [comment]
Looks good to me.

**Comment by GeraldJansen** [comment]
Concerning consistency and clarity of the rules for raw fact parsing, in the non-datetime parts, I had proposed:
`activity name[@category[, description] [#tag1] ... [#tagn]]`.
My idea was that requiring @category before an optional description or tags would provide an easy solution to the problems of including a #tag (#423)  or a comma (#280) in the activity name. I.e., parsing for description or tags only considers content after '@'. (Yes, I know, another interface change.) An alternative would be to allow #tag and comma embedded in the activity name only when an @category is given explicity.

Personally I don't use these features, but I still think it would be useful to define the parsing rules clearly somewhere, perhaps [here](https://github.com/projecthamster/hamster/wiki/Entering-activities), not just in the code.

**Comment by mwilck** [comment]
The '#' could be solved by always interpreting the first non-datetime item as the activity. If that's not the case, it's actually a bug, IMO. The comma is more problematic. I personally would put the description last:

    name[@Category] [#tag1] [#tag2] ... [description]

We wouldn't even need a comma in this scheme, the description would start at the first token after the activity that doesn't start with '#'. Or am I overlooking anything?

**Comment by ederag** [comment]
Thanks for the suggestions.
#465 has just been created to continue discussion about general parser format,
and keep this issue for date/time only.

**Comment by ederag** [comment]
Hopefully fixed: https://github.com/projecthamster/hamster/pull/482#issuecomment-562962375
