### ISSUE TITLE
What does this button do?

### ISSUE THREAD

**Issue by Forage** [projecthamster/hamster#447]
In the main UI there are four buttons at the top right.
![Screenshot from 2019-09-19 15-05-45](https://user-images.githubusercontent.com/550915/65247949-a6af7180-daf1-11e9-8818-c2b036cfc01b.png)
The second one does nothing what so ever. What is it's purpose?
It would be good to give them all a tool-tip to know what they do and how/when they are supposed to work.

**Comment by GeraldJansen** [comment]
Yes, tool-tips would be great, as would improved documentation.  The + button opens the "Add activity" dialog (as do ctl-+ and ctl-n). The second button is a small stop sign and means "Stop tracking" the currently ongoing activity (if any; also performed by ctl-space).

**Comment by Forage** [comment]
In that case, if possible, it would be better that the button is only enabled when there's an actual activity ongoing.

**Comment by ederag** [comment]
Solved by @GeraldJansen in PR #454.
Thanks !
