### ISSUE TITLE
Use Wiki as temporary homepage

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#450]
Could we temporarily change the homepage link at the top of https://github.com/projecthamster/hamster from http://projecthamster.org to the Wiki page https://github.com/projecthamster/hamster/wiki? 

The wiki page is far from optimal as a project homepage, but at least it doesn't look abandoned and anyone can improve it and add sub-pages, without the overhead of pull requests.

**Comment by ederag** [comment]
To me the front page is the [README.md](https://github.com/projecthamster/hamster/blob/master/README.md). Then chained issues (maybe make #433 sticky) for general discussions about progress.
What would you add to the wiki ?

It would be great if someone would update the site.
It can be recommended to ask kindly @elbenfreund (maybe by private mail) 
to get write access to the [hamster-website](https://github.com/projecthamster/hamster-website).

Until then, I would just remove the link...
... wait, the point is moot, as I do not have the rights to edit this part :smile:.

**Comment by GeraldJansen** [comment]
Most software projects have a general purpose homepage to present the software to a more general public than the more technical people that tend to read README's on github. What should it have? I don't know but perhaps some more screenshots, a "past, present and future" overview, links to documentation, etc. In this respect the old https://projecthamster.wordpress.com/about/ was helpful back when I started looking into Hamster

**Comment by GeraldJansen** [comment]
Closing for infeasibility.
