### ISSUE TITLE
Need python3-xdg in Debian Testing

### ISSUE THREAD

**Issue by leblowl** [projecthamster/hamster#459]
Installing in Debian testing, I followed the instructions in the README by installing dependencies, then building and installing Hamster. Upon first launch, I received the following error:
```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
  File "/usr/lib/python3/dist-packages/hamster/reports.py", line 33, in <module>
    from hamster.lib.configuration import runtime
  File "/usr/lib/python3/dist-packages/hamster/lib/configuration.py", line 30, in <module>
    from xdg.BaseDirectory import xdg_data_home
ModuleNotFoundError: No module named 'xdg'
```
Installing package `python3-xdg` solved it for me. I sort of rushed through installing the deps, but if I didn't make any other mistakes, then this new dependency should probably be added to the README.

**Comment by ederag** [comment]
Thanks for the report and thanks to Gerald for the PR !
