### ISSUE TITLE
Package for flathub

### ISSUE THREAD

**Issue by pwithnall** [projecthamster/hamster#462]
Thanks for reviving Hamster! The new version could get out to a lot of users very quickly if it were packaged for [flathub](https://flathub.org/home), [as a flatpak](http://docs.flatpak.org/en/latest/first-build.html).

That would avoid users having to build it themselves, and avoid waiting for distributions to update their packaging (which typically takes half a year).

**Comment by ederag** [comment]
Thanks for your interest in this project.
The install process is relatively simple again, 
so packaging is of course welcome and supported
(please ask here if you need help, I'll reopen),
but current focus is on fixing hamster for existing users.
Closing for lack of manpower.

**Comment by rabin-io** [comment]
https://github.com/flathub/flathub/pull/2614
