### ISSUE TITLE
JFTR: Settings window won't open

### ISSUE THREAD

**Issue by WBTMagnum** [projecthamster/hamster#464]
After migrating my system to a new machine and "updating" from an old hamster installation (see https://github.com/projecthamster/hamster/issues/402#issuecomment-525253222) I was unable to open the settings window. After some digging around I realized that the `~/.gconf` and `~/.dbus' folders belonged to root. I'm unsure where I took the wrong turn, but in the end that does not matter that much now.

After changing ownership of the folder I was eventually able to open and edit settings again.

Interestingly no errors where thrown when trying to open the settings window. Fiddling around with log levels did not help either.

**JFTR:**
* Hamster was build in August 2019 via waf from GIT repo
* OS: Ubuntu 18.04.3 LTS

**Comment by WBTMagnum** [comment]
Since the issue has been resolved, I'm closing it.

**Comment by ederag** [comment]
Indeed, the old installation process (before #421) was sometimes installing `.gconf` as root in `$HOME`.
(thanks for pointing that `.dbus` could also be affected).

What does JFTR mean ?
Please avoid non-standard abbreviations 
(a search yields only "Joint Federal Travel Regulations", pretty sure it is not that :smile:)

**Comment by WBTMagnum** [comment]
Sorry for being unspecific. JFTR stands for "Just for the records". I was under the impression, that this is a quite common abbreviation. I updated the ticket accordingly.
