### ISSUE TITLE
Add Flatpak package

### ISSUE THREAD

**Issue by jasuarez** [projecthamster/hamster#474]
I'm wondering if there is any plan to provide a Flatpak version of Hamster.

This would be easier adding Hamster in those distros that for some reason or another have removed hamster package from their package list, or any dependency that Hamster is currently using but it is not anymore in the distro.

**Comment by GeraldJansen** [comment]
Please see #462 (duplicate).

**Comment by jasuarez** [comment]
Oh, right. I was looking in the open issues, not in the closed ones. Thanks!
