### ISSUE TITLE
Error with dbus type conversion on recent upgrade

### ISSUE THREAD

**Issue by matclab** [projecthamster/hamster#477]
I just upgraded Arch linux with
- python 3.8
- pygtk 2.24.0
- python-dbus 1.2.12

Running master I get the following errors:
- in hamster-cli
```
Traceback (most recent call last):
  File "/home/clabaut/contrib/hamster/src/hamster/edit_activity.py", line 375, in on_save_button_clicked
    runtime.storage.update_fact(self.fact_id, self.fact)
  File "/home/clabaut/contrib/hamster/src/hamster/client.py", line 177, in update_fact
    new_id =  self.conn.UpdateFactVerbatim(fact_id, dbus_fact)
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlite3.OperationalError: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "src/hamster-service", line 176, in UpdateFactVerbatim
    return self.update_fact(fact_id, fact) or 0
  File "/home/clabaut/contrib/hamster/src/hamster/storage/storage.py", line 76, in update_fact
    self.__remove_fact(fact_id)
  File "/home/clabaut/contrib/hamster/src/hamster/storage/db.py", line 722, in __remove_fact
    self.__remove_index([fact_id])
  File "/home/clabaut/contrib/hamster/src/hamster/storage/db.py", line 819, in __remove_index
    self.execute("DELETE FROM fact_index where id in (%s)" % ids)
  File "/home/clabaut/contrib/hamster/src/hamster/storage/db.py", line 911, in execute
    cur.
```
- Where hamster-service logs 
```
hamster.storage.db - INFO - removing fact #dbus.Int32(8432)
```

The same problem occurs with release v2.2.2.
 
I guess a conversion from dbus data went wrong.

**Comment by matclab** [comment]
Note that python-dbus was upgraded from 1.2.10-1 to 1.2.12-1

**Comment by matclab** [comment]
Adding `fact_id = int(fact_id)` at the first line of `__remove_fact` function solves the problem.

(I tried to do the conversion in `_dbfact_to_libfact`, but it was not enough.

**Comment by ederag** [comment]
Thanks for the report and the fix.

https://github.com/projecthamster/hamster/blob/6792b06589bb19c7207c06fb83a1e945a30ed6ba/src/hamster/storage/db.py#L817-L819
Did python-dbus drop the `__str__` overload for `dbus.Int32` ?

Would be nice to report upstream, but where is the development page ?

For anyone interested, the 1.2.12 version refers to dbus-python.
https://pypi.org/project/dbus-python/1.2.12/
That has nothing to do with the dbus interface given on the dbus site
https://www.freedesktop.org/wiki/Software/DBusBindings/#python
(which is the homepage given on the dbus-python pypi page above)

**Comment by ederag** [comment]
Found the dbus-python repo at the bottom of the [previous page](https://www.freedesktop.org/wiki/Software/DBusBindings/#python):
https://gitlab.freedesktop.org/dbus/dbus-python

The `__str__` is inherited from `builtins.int` here.
What is the ouput of
```python
python3 -c 'import dbus; print(dbus.Int32.__str__)'
```
on your system ?
Here (1.2.4) it gives `<slot wrapper '__str__' of 'int' objects>`.

And
```python
python3 -c 'import dbus; print(dbus.Int32(34))'
```
Here that prints `34`.

Finally, check if that comes from the python string format:
```python
python3 -c 'import dbus; print("{}".format(dbus.Int32(34)))'
```
Here that prints `34`.

**Comment by matclab** [comment]
Here are the results:
```
python3 -c 'import dbus; print(dbus.Int32.__str__)'; python3 -c 'import dbus; print(str(dbus.Int32(34)))';  python3 -c 'import dbus; print(str(int(34)))'
<slot wrapper '__str__' of 'object' objects>
dbus.Int32(34)
34
```
So, there seems to have been a change in `dbus.Int32__str__`.
I've checked python3.8 changelog, but I didn't see anything that seems closely related.

**Comment by matclab** [comment]
I tried to open a bug report in https://gitlab.freedesktop.org, but I was unable to open an account. i'll try again later in the day.

**Comment by matclab** [comment]
Issue [31](https://gitlab.freedesktop.org/dbus/dbus-python/issues/31) opened upstream.

**Comment by matclab** [comment]
Upstream issue is closed with a fix (tested locally with hamster). I guess we can close this issue.

**Comment by GeraldJansen** [comment]
Hmm, other Hamster users may be hit with this. For example, debian testing has python3.8 and python3-dbus-1.2.12. It may be better to either leave this open or integrate the work-around into hamster.

**Comment by ederag** [comment]
[dbus-python-1.2.14](https://gitlab.freedesktop.org/dbus/dbus-python/-/tags/dbus-python-1.2.14) has been tagged.
So this is fixed upstream (nice reactivity from the dbus-python devs), 
and should be quickly incorporated into these leading edge distributions.
(would this assumption be wrong, 
 a PR with the workaround together with an inline comment pointing to the upstream issue 
 would be acceptable)

No strong objection to follow your advice and keep this issue open for a little while though,
since it is easy to forget to search into closed issues as well.

Thanks @matclab for the exemplary report, investigation and part of the quick upstream fix !

**Comment by matclab** [comment]
Thanks @ederag, both hamster and dbus-python community was very supportive. I'd like to take more time to help improve hamster has it is my daily driver, but time flies too fast !

**Comment by ederag** [comment]
debian testing has [1.2.16](https://packages.debian.org/sid/python-dbus) now 
(1.2.14 was tagged two months ago), so it seems be safe to close.

@matclab 
>  I'd like to take more time to help improve hamster

You already did. Quality feedback is precious, so testing PRs every now and then,
or just following the `master` branch would also be great.

**Comment by acheype** [comment]
Hi !
Just to let you know I had a problem with the assert you wrote to verify that dbus-python version is bigger or equal than 1.2.14.

```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 40, in <module>
    from hamster import client, reports
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 48, in <module>
    assert not (
AssertionError: python3.8 changed str(<dbus integers>).
       That broke hamster (https://github.com/projecthamster/hamster/issues/477).
       Please upgrade to dbus-python >= 1.2.14.
```
But the followed package is installed :
python3-dbus                                     1.2.16-1build1

In my case, the problem in the assert is that LooseVersion(dbus.__version__) is equal to 1.2.8. ??? I have no idea why...
I have comment the lines of this assert and hamster works well now.

**Comment by acheype** [comment]
I'm sorry, my mistake !
It was effectively the 1.2.8 which was loaded from my local package : ~/.local/lib/python3.8/site-packages
I deleted it with pip3, and now python3 load the 1.2.16 version.
