### ISSUE TITLE
Cannot remove category with edit/update

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#478]
With current master, after creating an activity with a category and then editing or resuming the activity, clearing the category and saving, the previous category remains unchanged. Changing the category to a different value works fine, but completely removing any category fails. 

(Note that this behaviour pre-dates PR #473. For example, I also checked 1ddd6bd.)

**Comment by GeraldJansen** [comment]
Studying storage/db.py, functions `__change_category()` and `__get_activity_by_name()`, it seems that this is a "feature". If an activity name is entered without category, the activities table is searched by activity name and if found then the most recent associated category id is picked up and used for the new activity. Just guessing, but perhaps this was seen as a convenience in the past before auto-completion. Not sure where to go from here.

**Comment by ederag** [comment]
Not sure yet, but this feature seems good.
To be investigated more after the parser changes,
but we should probably use more the unsorted id:
https://github.com/projecthamster/hamster/blob/a626f40f7e34f8e597d5459cf6f4a5eceebc9456/src/hamster/storage/db.py#L43
so there is a clear difference between `None` (meaning we want all categories) and `-1` (unsorted).
