### ISSUE TITLE
hamster-cli is complaining about a missing fact.check

### ISSUE THREAD

**Issue by tykeal** [projecthamster/hamster#504]
I'm running on an install of the current master (SHA 199aee94c8161a597d9ce8e02e2d1b488260a9dd) when trying to update / add entries I get the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 366, in <module>
    getattr(hamster_client, command)(*args.action_args)
  File "/usr/bin/hamster", line 140, in track
    self.start(*args)
  File "/usr/bin/hamster", line 152, in start
    fact.check(default_day=stuff.hamster_today())
AttributeError: 'Fact' object has no attribute 'check'```

**Comment by ederag** [comment]
Indeed, thanks for the report.
Please hold on :smile:

**Comment by ederag** [comment]
Should be fixed by #505.

**Comment by tykeal** [comment]
What can I say, I upgraded to Fedora 31 and was seriously surprised to find my hamster unavailable so I went to install it manually! Then I ran into this ;)

**Comment by ederag** [comment]
Testers  were less available during the holidays, and this is a period of intense development,
precisely to get hamster back into all distributions.
So master is less stable than usual these times. Hence early testing is even more welcome :wink:

**Comment by tykeal** [comment]
It's ok, I'm fine with that. I'm a sysadmin / release engineering ;) just wasn't expected to suddenly be one for a project I've been using for years!

**Comment by tykeal** [comment]
Just pulled and tested, it fixes my problem!
