### ISSUE TITLE
Checking for program 'glib-genmarshal'   : not found

### ISSUE THREAD

**Issue by aasutossh** [projecthamster/hamster#506]
After installing dependencies, when I run ./waf configure build I get the following error.
```
./waf configure build
Setting top to                           : /home/aasutossh/git/hamster 
Setting out to                           : /home/aasutossh/git/hamster/build 
Checking for program 'glib-genmarshal'   : not found
```
Tried searching for the issue, no lead.
Thank you.

**Comment by ederag** [comment]
That's a new one.
*What is your system ?*
In general, please specify the distribution and the version of hamster you are using.
You may try to type `glib-genmarshal` in a terminal, 
that usually gives instructions on how to install the missing program.
Please paste back these instructions here, so others can benefit.

**Comment by aasutossh** [comment]
So sorry.
I am using pop os 19.10.
I used git clone to get the hamster(must be latest version).

Writing `glib-genmarshal` in the terminal outputs the following:
```
Command 'glib-genmarshal' not found, but can be installed with:

sudo apt install libglib2.0-dev-bin
```
Installing this worked for me.
Build successful.
Thank you so much.

**Comment by ederag** [comment]
Thanks for the success feedback.

Note that from `apt info libglib2.0-dev`
>  This package is needed to compile programs against libglib2.0-0. It contains
 development utilities typically run during compilation and should not be
 installed directly. Use libglib2.0-dev instead.

So you might want to issue `sudo apt install libglib2.0-dev` to be more standard.

**Comment by aasutossh** [comment]
Well, snap way seems much easier.
I went for snap way.
Thanks.
