### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by zendre4** [projecthamster/hamster#508]
Hello,

I don't know if this is already planned or not, but it would be interesting to offer a Flatpak version.

This for the following reasons:
- Flatpak is a technology more and more widespread
- Flatpak is supported by many distributions and only requires a single build to be compatible with these different distributions.
- This simplifies the installation/update process.
   
Moreover a runtime containing the Gnome dependencies already exist.

Thanks.

**Comment by ederag** [comment]
https://github.com/projecthamster/hamster/issues?utf8=%E2%9C%93&q=is%3Aissue+flatpak
