### ISSUE TITLE
Snap : Not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by mrpouletcurry** [projecthamster/hamster#511]
Hey,

I install today your snap package and nothings happend. None windows is open.

**Comment by ederag** [comment]
@extraymond is responsible for the [snap package](https://github.com/extraymond/hamster-snap) (thanks !).

How did you try to launch hamster ?

Meanwhile, [installing from sources](https://github.com/projecthamster/hamster#install-from-sources) should work.

**Comment by extraymond** [comment]
Sorry! I forgot to tell people to manually connect system-observe plug.

Try snap connect hamster-snap:system-observe
Or do the equivalent from the software store(assuming gnome software center with snap plugin)

**Comment by extraymond** [comment]
@mrpouletcurry  After you connect the plug, make sure the old hamster related services is killed before you launch it again.

There will be two python processes you can find that related to hamster-*-service.

**Comment by mlippert** [comment]
@extraymond Thanks, I just installed the snap on kubuntu 18.04 `snap install hamster-snap` and it wasn't working. I ran the `snap connect hamster-snap:system-observe` command and now it shows up. Maybe update the readme?

Anyway thanks all for this, I'm using the hamster applet on 16.04 (actually Linux Mint 18.3 KDE) and wasn't sure what I was going to do for time tracking when I upgraded to 18.04 or 20.04. Hamster gives me just the right level of time tracking.

**Comment by extraymond** [comment]
@mlippert 

Since the instruction is specific to snap, I think leaving it to the snap's pages will allow the README of this project to stay clean.

No problem, I love hamster too. Since I know it's now being properly maintained, not having to worry about updates is my motivation as well. I'm on 19.10 now and it's working as well.

**Comment by extraymond** [comment]
@mrpouletcurry  Could you try the instruction again? I think this is solved if first try to connect it and launch with the services killed.

**Comment by ederag** [comment]
@mlippert The link was a bit too separated from the text, indeed. 
With a colon the relation should be clearer (939c1bbc32fb434b4ec66aa749063ccc02c2f6a7). Thanks for reporting.
