### ISSUE TITLE
Multiline description can not be entered

### ISSUE THREAD

**Issue by priiduonu** [projecthamster/hamster#520]
Installed from master, running on Fedora 31.
When newline is entered in the description field, the Save button is deactivated after typing anything else.
Therefore can not use multiple lines in description field.

**Comment by ederag** [comment]
Confirmed, thanks for the report !

**Comment by ederag** [comment]
Should be fixed by #522.

**Comment by priiduonu** [comment]
Confirmed working again, thanks for Your effort!
