### ISSUE TITLE
Unknown method: DescribeAll

### ISSUE THREAD

**Issue by felipet** [projecthamster/hamster#526]
Hi! I installed hamster from source sin Fedora 31 and I get the following error while opening the app:

 ```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 448, in <module>
    app.register()
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib64/python3.7/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: DescribeAll is not a valid method of interface org.gtk.Actions
```

**Comment by ederag** [comment]
Thanks for the report.
This happens when a dbus service is already running with the same id as the application to register.

What is the output of the following command ?
```bash
pgrep -af hamster
```
It should be empty (if there is a windows-service listed, that's the issue).

Did you [kill the hamster daemons](https://github.com/projecthamster/hamster#kill-hamster-daemons) ?

**Comment by ederag** [comment]
The instructions should not mention launching hamster-windows-service at all.  Fixed by 115e3587ba9389d7eb154987a5cb7440eeb924cc

**Comment by ederag** [comment]
@felipet With the version checks introduced in #528, this should happen any longer;
could you please check again ?

**Comment by ederag** [comment]
@felipet I'll reopen if it is not fixed.
