### ISSUE TITLE
Icon missing / App tracking broken in Gnome/Wayland

### ISSUE THREAD

**Issue by bochecha** [projecthamster/hamster#541]
I think #538 broke app tracking somehow.

I just updated and restarted Hamster, now GNOME Shell doesn't manage to figure out that the running instance corresponds ot the desktop file.

Here's what I see in the dash, observe how the running icon is separate from the launcher:

![dash-hamster](https://user-images.githubusercontent.com/272170/74048101-d80dd880-49d1-11ea-8bac-e99331883f7f.png)

And here's alt+tab:

![alt-tab-hamster](https://user-images.githubusercontent.com/272170/74048133-eb20a880-49d1-11ea-8209-32a93d40b4b4.png)

**Comment by ederag** [comment]
Just to bisect, that was not the case when you [reviewed the first commits](https://github.com/projecthamster/hamster/pull/538#discussion_r374547185) ?

**Comment by ederag** [comment]
Learned a few things about icons,
but that's actually a Gnome/wayland issue:
![Screenshot_20200207_215411](https://user-images.githubusercontent.com/10962809/74065153-84f94d00-49f4-11ea-8ad9-b1144848ddda.png)
Under Gnome/Xorg, the icon is there:
![Screenshot_20200207_215708](https://user-images.githubusercontent.com/10962809/74065279-cab61580-49f4-11ea-8a83-051be63f8a03.png)

**Comment by ederag** [comment]
Renaming done in #542 , did not solve anything. Giving up.

**Comment by bochecha** [comment]
> Just to bisect, that was not the case when you reviewed the first commits ?

I never tested those, I only reviewed the code change.

> Renaming done in #542 , did not solve anything. Giving up.

Yes, because I'm pretty sure it's an app tracking issue, not an icon one: GNOME Shell doesn't associate the running instance with the desktop file used to launch it. The missing icon is a side-effect of that app tracking problem.

**Comment by ederag** [comment]
Understood, I now see why the previous title made sense.
In my case I do not see the splitting 
(when launching from the activities search, there is a single entry appearing to the left,
no icon at all).
So let's keep the current title as in both cases an icon is missing. But agreed, there is more to that.
What is your distribution / desktop ?

It might be related to the icon though, as I suspect that looking at the icon name is one of the heuristics
mentioned in https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased
> Note: it's recommended that you use the same identifier for 
your application id, .desktop file, .service file, and application icon. 
This allows the Shell to match all your assets to the application,
and prepares your application for sandboxing.

They  also say
> Ensure that your application's .desktop file has StartupNotify=true

Would you try ?

**Comment by bochecha** [comment]
> In my case I do not see the splitting
> (when launching from the activities search, there is a single entry appearing to the left,
no icon at all).

In the screenshot above I have two entries because the one with the icon is the launcher that I added to the dash ("Add to Favourites"), the one without icon is the running instance.

Having an icon for the second entry would still be wrong, because there really needs to be a single entry for both the launcher and the running instance.

>  What is your distribution / desktop ?

Fedora Workstation 31, with GNOME 3.34.

>> Ensure that your application's .desktop file has StartupNotify=true
> 
> Would you try ?

I will try on Monday. (I only have Hamster on my work computer)

I also asked the GNOME Shell developers, and they had this to day:

```
<jadahl> iirc with gtk you should set.. something.. to that app id. cant remember exactly what, maybe g_set_prgname()?
```

I can also try that on Monday.

**Comment by ederag** [comment]
> there really needs to be a single entry for both the launcher and the running instance

Indeed, that's why I added "agreed, there is more to that"
 I just meant that someone facing this would certainly find this issue,
since the icon would be missing as well.
Or am I missing a point (that's highly possible) ?

About the prgname, it looks like the `hamster --name` attempt above.
Worked, but the result was too ugly.

> I can also try that on Monday.

That would be great !
I'm going to release `3.0-beta` tomorrow to keep the schedule and 
hopefully attract the attention of a packager for ubuntu.
We'll have about one week before `3.0-rc1`.

**Comment by mwilck** [comment]
I think I found the problem. 

GtkApplication must call `GLib.set_prgname()` explicitly in `startup()`. See [gtk#653](https://gitlab.gnome.org/GNOME/gtk/issues/653), [set_prgname() example](https://www.programcreek.com/python/example/87806/gi.repository.GLib.set_prgname).
You'd expect GtkApplication to set this automatically from the application_id, but that's not the case.

Basically, this is equivalent to using the `--name` option. Unlike @bochecha, this does *not* cause the ugly `org.gnome.Hamster.GUI` name to be displayed in the GNOME panel.

**Comment by bochecha** [comment]
> I think I found the problem.
> 
> GtkApplication must call `GLib.set_prgname()` explicitly in `startup()`. See [gtk#653](https://gitlab.gnome.org/GNOME/gtk/issues/653), [set_prgname() example](https://www.programcreek.com/python/example/87806/gi.repository.GLib.set_prgname).
> You'd expect GtkApplication to set this automatically from the application_id, but that's not the case.

Right, this is what we were discussing just above, and I was supposed to test it on Monday but completely dropped the ball.

Thank you for confirming.

> Basically, this is equivalent to using the `--name` option. Unlike @bochecha, this does _not_ cause the ugly `org.gnome.Hamster.GUI` name to be displayed in the GNOME panel.

I hadn't tested that, @ederag was the one observing this. I get the same as you, using `--name org.gnome.Hamster.GUI` works just fine for me.

IMHO the best fix is to call `GLib.set_prgname()` explicitly, because it fixes all cases, including when people run Hamster in the CLI.
