### ISSUE TITLE
integration with toggl

### ISSUE THREAD

**Issue by Fedaykin86** [projecthamster/hamster#55]
Because i'm using Toggl in my work it would be nice to write some plugin that integrates hamster with toggl.com (https://www.toggl.com/public/api).
Eventually if somebody would tell where to look i can do it myself

**Comment by ni-ka** [comment]
This would actually be awesome, many jobs today require time tracking on the go as well as focused desk time

**Comment by mwilck** [comment]
@ni-ka, all I can say is "please provide patches". Support for a 3rd party proprietary tool is not highest on the maintainers' agenda, even if the idea sounds nice indeed and toggl has a public API.

Interestingly, hamster is currently suggested as [alternative to toggl](https://alternativeto.net/software/toggl/?license=opensource).
