### ISSUE TITLE
Minor packaging issues (waf)

### ISSUE THREAD

**Issue by mwilck** [projecthamster/hamster#550]
I've been working on the openSUSE package for 3.0-beta, and found that two "features" of the new waf code are rather non-helpful for packagers:

 * automatic updating of the icon cache
 * automatic compilation of gsettings schemas

For packaged hamster, both need to be done at **installation time**, not at built time. Distros usually have macros or scripts in place to do this automatically. I can see that doing these steps is useful for people who run the manual installation procedure. For packagers, these steps create useless files that need to be removed again before creating the actual package. Perhaps we could find a way to disable these steps for distro builds?

If not, no worries, I've quickly patched this out and can continue to do so.

**Comment by matthijskooijman** [comment]
@mwilck for the Debian package, I was also looking at this issue. However, I noticed that the `--skip-gsettings` option that is now available skips the gsettings completely. That is, it does not just skip compiling the schemas, it also skips validating and installing them, of which installing *must* happen at build time obviously, and validating seems useful. This does seem like a limitation of waf, though, which [does not seem to have a way to separate installation from compilation](https://github.com/projecthamster/hamster/blob/afbec4c620b2123cc3562f52de02c8b50cc8ef82/waflib/Tools/glib2.py#L251-L329).

I can of course install the schemas separately (and skip validation, or also do that separately), but I then wonder if it would not be better to just let waf do everything and then remove the compiled schemas again?

@mwilck @hedayat, how did you solve this in your packages? Also, is your packaging work available for browsing online somewhere, to draw some inspiration from? :-)

**Comment by mwilck** [comment]
@matthijskooijman, I used patches:

 * [waf-skip-gsettings-schema-compilation.patch](https://build.opensuse.org/package/view_file/home:mwilck:branches:Office/hamster-time-tracker/waf-skip-gsettings-schema-compilation.patch?expand=1)
 * [wscript-don-t-update-icon-cache.patch](https://build.opensuse.org/package/view_file/home:mwilck:branches:Office/hamster-time-tracker/wscript-don-t-update-icon-cache.patch?expand=1)
 * [openSUSE build service](https://build.opensuse.org/package/show/home:mwilck:branches:Office/hamster-time-tracker) package directory

Note that I created them before I opened this issue. I have to confess that I didn't test @ederag's fix from @565, otherwise I'd probably noticed what you just found, too.

**Comment by hedayat** [comment]
@matthijskooijman No, actually I've not yet started the packaging. :P
