### ISSUE TITLE
start time ignored from xfce-hamster-plugin

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#560]
When entering a verbatim activity such as `10:15 work@home` from the xfce-hamster-plugin, the specified starting time is ignored and instead the current time is used. The same happens using a relative time such as `-20`.

@mwilck Would you mind checking if this works with the gnome shell extension?

Note: testing hamster version v3.0-beta-16-gc78079f8+ (i.e. with 0cffe9c temporarily reverted).
Note: to get the plugin working, I had to `./configure --prefix=/usr --with-icon=hamster`.

**Comment by ederag** [comment]
#491 discussion seems relevant here.

**Comment by GeraldJansen** [comment]
Yes, sorry I missed that. However, I don't really understand the resolution.

**Comment by ederag** [comment]
Considerations like https://github.com/projecthamster/hamster/issues/491#issuecomment-564500251 and the following comments 
scared me away from doing the obvious thing: treat 0 as "bypass".
Reading that again, I really do not understand why either.
It's terribly tempting to try #491 again, isn't it ?

**Comment by GeraldJansen** [comment]
Unfortunately I don't have time to dig into this. I understood that previously it was possible to specify the start time from the plugin (as in my example above) and the whole string was just sent to hamster for parsing. Now the start time seems to get silently stripped and ignored, which seems like a strange behaviour.

I actually don't use xfce-hamster-plugin and don't know if anyone else does either (at most a handful I'd guess). I just thought I'd test it a bit together with v3.0-beta and happened by chance on this surprising behaviour, so I reported it. Given that it seems to be a known dbus interface issue, I'd say we can just close this.

**Comment by ederag** [comment]
Please keep it open. "surprising behaviour" means a lot, and I agree.
I'm going to redo #491 since I have learned lately to take some scary comments with a grain of salt.
Some concerns are sometimes completely "theoretical".

**Comment by mwilck** [comment]
> @mwilck Would you mind checking if this works with the gnome shell extension?

Confirmed. This is how the extension calls the `AddFact` API:

    method call time=1581690763.169630 sender=:1.22 -> destination=:1.51 serial=558 path=/org/gnome/Hamster; interface=org.gnome.Hamster; member=AddFact
        string "13:10 act@Cat"
        int32 0
        int32 0
        boolean false

So I can't confirm that the time is getting stripped. It's being sent to hamster but ignored. @ederag, you can test this with D-Feet by sending e.g. `"12:50 cat@Fact", 0, 0, False` as input.

**Comment by mwilck** [comment]
@ederag, the solution from #491 (actually, #492) would fix this. As you can see in the previous comment, the shell extension always passes "0" for start and end time, and so does the xfce plugin if I understand correctly. One might think that the extension abuses the API. But I believe it's different - the text entry of the shell extension was originally meant to pass an acitivity string only. Some time in the past, hamster started to parse this string and derive a start time, and people got used to it. I personally had never discovered this "feature" and only started using it after being involved in #491.

**Comment by ederag** [comment]
@mwilck Thanks, interesting, let's follow-up in #492 ?

**Comment by ederag** [comment]
It seems to work fine with the extension 
(thanks a lot @mwilck for the early testing, that's a relief !). 
Let's hope it is the same under xfce.
