### ISSUE TITLE
handling new activity same as ongoing activity

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#564]
Testing xfce-hamster-plugin, I noticed a minor difference in behaviour when (distractedly) entering a new activity that is the same as the current ongoing activity. 

1. Hamster GUI: new activity is silently ignored
2. dbus interface (xfce plugin): ongoing activity is terminated and a new adjacent activity is started
3. CLI: raises AssertionError (assert id_ > 0, "failed to add fact")

This issue is unimportant and certainly not urgent (in my opinion). For me it would be fine to silently ignore (or log.info) this case consistently, as long as a note is added to a help page (splitting and merging?).

**Comment by ederag** [comment]
Thanks for the report, as you said not urgent, but worth solving, especially 3.
1. For other readers: this is the standard behavior. 
     The requested A:s2.. is already included in the first A:s1.., so there is no need to add anything.
     To get two facts, the first one has to be stopped manually.
2. This is a design choice of the xfce plugin IMO, up to them.
     Choosing this as the default behavior in hamster would prevent any automatic merging.
3. Indeed, that error message is cryptic in this case.

There are several ways to solve the third point.
- If the requested fact had no end,
  look at an ongoing fact; if it is equal to the requested one, then all went well actually.
- Improve add_fact to also return a message, but add_fact should never fail
   because check_fact is there to ascertain that. Which leads to the next point:
- Improve check_fact to indicate something like
  "requested fact is already included in the on-going fact, nothing to do".

**Comment by GeraldJansen** [comment]
> 2. This is a design choice of the xfce plugin IMO, up to them.

I rather doubt there was any conscious design decision about this. Instead, I suspect this client (and perhaps also the gnome shell extension) simply fire off a dbus AddFact request with whatever the user types in the input field. I thought the CLI uses - or used to use - the same dbus interface and that the same checks would be applied. (Sorry for all the unchecked suppositions.)

As I said, my preference would be for consistency, i.e. all three input methods to result in the same behaviour of silently ignoring the input.

**Comment by ederag** [comment]
> I suspect this client (and perhaps also the gnome shell extension) simply fire off a dbus AddFact request with whatever the user types in the input field.

I suspect the contrary: stop current, *then* AddFact.

> I thought the CLI uses - or used to use - the same dbus interface and that the same checks would be applied.

It does.

**Comment by GeraldJansen** [comment]
>I suspect the contrary: stop current, then AddFact.

Hmm, I just checked this with dbus-monitor. The only dbus request issued from the xfce plugin is:
```
... interface=org.gnome.Hamster; member=AddFact
   string "work"
   int32 0
   int32 0
   boolean false
```
AFAICT, no explicit action was taken by the plugin to stop the ongoing task.

**Comment by ederag** [comment]
Path taken from the cli `hamster add work`:
https://github.com/projecthamster/hamster/blob/c3ae7b1e2c86e924f549fc334ebb7c31089e637b/src/hamster-cli.py#L218
then
https://github.com/projecthamster/hamster/blob/c3ae7b1e2c86e924f549fc334ebb7c31089e637b/src/hamster/client.py#L220
to
https://github.com/projecthamster/hamster/blob/c3ae7b1e2c86e924f549fc334ebb7c31089e637b/src/hamster-service.py#L176

While the xfce dbus request calls
https://github.com/projecthamster/hamster/blob/c3ae7b1e2c86e924f549fc334ebb7c31089e637b/src/hamster-service.py#L138
By the way there is no such thing as a default argument in dbus, so to be clearer, the last one should be a positional argument. Does not change anything though, as this argument is always given by dbus.

so AddFact and AddFactJSON behave differently ?
But they both call the same `add_fact` in the end.
Is there something different in the fact passed to `add_fact` ?

**Comment by ederag** [comment]
Well, can't reproduce via d-feet (tested with b10c9bb273a1cb77f8fc52027118505512140786)

![Screenshot_20200216_123307](https://user-images.githubusercontent.com/10962809/74603881-8e4f7d00-50b8-11ea-9a53-5ec8998bcb48.png)

the server logs
```
hamster.storage.db - INFO - same fact, already on-going, nothing to do
```

**Comment by GeraldJansen** [comment]
Yikes. Much to my embarassment, I can also not reproduce. I'm afraid the ongoing activity was 'work@home' and the new activity was just 'work'  when it originally happened. The activities looked the same in the plugin because the category is only shown separately in the totals line.

Sorry to have distracted you in this very busy time.

**Comment by ederag** [comment]
It's OK, good to see you around, the balance is still largely positive !
That leaves only the error message to improve (last point in https://github.com/projecthamster/hamster/issues/564#issuecomment-586579128), which can wait.
