### ISSUE TITLE
Crash in hamster-window-server: 'NoneType' object has no attribute 'set_cursor'

### ISSUE THREAD

**Issue by matthijskooijman** [projecthamster/hamster#571]
I was running the latest code, and Gnome showed me a crash report. Looking inside, I found that hamster threw an exception:

	org.gnome.Hamster.WindowServer[9261]: Traceback (most recent call last):
	org.gnome.Hamster.WindowServer[9261]:   File "/usr/lib/python3/dist-packages/hamster/lib/graphics.py", line 2136, in __on_mouse_move
	org.gnome.Hamster.WindowServer[9261]:     self.__check_mouse(event.x, event.y)
	org.gnome.Hamster.WindowServer[9261]:   File "/usr/lib/python3/dist-packages/hamster/lib/graphics.py", line 2094, in __check_mouse
	org.gnome.Hamster.WindowServer[9261]:     self._window.set_cursor(gdk.Cursor(cursor))
	org.gnome.Hamster.WindowServer[9261]: AttributeError: 'NoneType' object has no attribute 'set_cursor'

This happened when I was editing a running activity (IIRC I changed the title). I *think* I just pressed "enter" to confirm the edit (after the crash, hamster-windows-service was resarted and the edit was applied).

I know this is not so much to go on, but I wanted to at least record the backtrace somewhere. Maybe this helps someone to find the problem (or maybe others seeing the same can add more info).

This happened running commit 7138d1aff96dbd0d15410bfd26284904885e672e, so effectively 3.0.

**Comment by ederag** [comment]
Thanks for reporting.
Just to be sure, the issue arises when editing a specific fact from the gnome-shell-extension,
that opens the "Edit activity window", then changing something and hitting enter ?
I did not manage to reproduce from d-feet. 
No obvious bug in the code *at first sight*. Need to follow from the stack trace upward to get a hint.
`if self._windows:` would fix it locally, but let's try to find out the root cause first.

It would be good to gather more information indeed, if that happens again.

**Comment by ederag** [comment]
Found out part (if not all) of the explanation. The `_window` is stored too late.
A `motion-notify-event` (mouse move) happened before the `do_draw` is entered.
https://github.com/projecthamster/hamster/blob/ff1ab0e8addc19f7d3b84af2077947ae8fd8df61/src/hamster/lib/graphics.py#L1986
The `_window` should be stored when [`realize`](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/Widget.html#Gtk.Widget.realize) is emitted. I'll test and file a PR.

**Comment by matthijskooijman** [comment]
Sounds plausible. Your PR also sounds consistent with your implementation, though I have no GTK experience to really contribute a proper review. Thanks for picking this up, though :-)

**Comment by ederag** [comment]
Thanks for the feedback !
