### ISSUE TITLE
Off-by-one-day in hamster export tsv

### ISSUE THREAD

**Issue by matthijskooijman** [projecthamster/hamster#576]
I recently upgraded to hamster 3.0.0, and now noticed `hamster export tsv` started to return slightly too much data. It seems there is an off-by-one-day error in the "to" date. For example:

```
matthijs@grubby:~$ hamster export tsv 2020-01-21 2020-01-22
activity        start time      end time        duration minutes        category        description     tags
Reizen  2020-01-21 08:55        2020-01-21 10:00        65.0    MKIT            Work
Reizen  2020-01-22 07:55        2020-01-22 08:26        31.0    MKIT            Work
Reizen  2020-01-23 18:09        2020-01-23 19:09        60.0    Day-to-Day
```

(I trimmed some extra activities for privacy and clarity)

This should, AFAIU (and it always did) return activities on the 21st and
22nd, but it also includes the 23rd. I originally noticed this with
february 29th and suspect an issue with leap years, but it seems to
happen with any date I've tried so far.

I have not investigated yet, first wanted to at least document this.
Maybe someone else can try to reproduce this?

**Comment by GeraldJansen** [comment]
I can confirm (using latest `hamster version` v3.0.1-1-gafbec4c6). 
The same happens when asking for a single date, for example: `hamster export tsv  2020-02-27`.
It also happens using the GUI export menu item and selecting specific start-end range from the calendar.

**Comment by mwilck** [comment]
Do we know if this is a regression in 3.0, and if yes, caused by which commit?

**Comment by mwilck** [comment]
I've just tried with 2.2.2, and can't reproduce this issue.

**Comment by GeraldJansen** [comment]
> caused by which commit?
Probably #514 and specifically c5178eb. Hopefully @ederag will confirm and provide a better fix :-)

**Comment by ederag** [comment]
#580 is an alternate proposition.
Don't get the wrong impression, I'm beginning to be absorbed by new activities.
It just was intriguing and easy.
