### ISSUE TITLE
hamster-service not autostarting after 3.0.1 install

### ISSUE THREAD

**Issue by farao** [projecthamster/hamster#578]
I installed version 3.0.1 as explained in the README and the installation was successful. Now, when I start "hamster" on the command line, it doesn't start hamster and after a while it shows DBUS exceptions suggesting that it can't connect to the hamster-service.

Indeed, hamster-service is not started when calling "hamster". It is installed in /usr/libexec/hamster/hamster-service and when I start it manually, hamster works fine - but I guess this is not the intended behaviour.

System: Fedora 31
Hamster version: 3.0.1

**Comment by mwilck** [comment]
Please check the dbus service definition files under `/usr/share/dbus-1/services/`. Do they set the correct path in the "Exec=" line? It might be a `/usr/lib/` vs. `/usr/libexec` issue.

**Comment by farao** [comment]
You are correct, that was it (it was /usr/lib64/..). For me it works now, thanks! Why did it choose the wrong path?

**Comment by mwilck** [comment]
I think you could customize that using the `--libexecdir` option to waf. The point here is that on some distributions, the defaults for libexecdir have changed. That's why it makes sense for wait for hamster to be packaged by your distribution, to have other people figure it out for you :smiley:

**Comment by farao** [comment]
That's true! Just wanted to point out that if there's an easy way to check and adapt this during the configure/build step it might be easier for people to use it from Github directly - in my distribution (Fedora 31) for example, hamster is not packaged at all.

**Comment by matthijskooijman** [comment]
I think that installing from git should at least have working (i.e. consistent) defaults. So if you did not customize any of these paths, then I would say this is a bug.

I think that the install produced consistent results on my system, so I guess there is some OS- or system-specific factor here?

Maybe one of the paths (e.g. the install path vs the one in the dbus files) has a fixed default and the other defaults to some OS-specific value?

**Comment by mwilck** [comment]
@matthijskooijman, I don't think there's a reliable way for **waf** to guess these things. This is why we need options like `--prefix` and `--libexecdir`. Every serious build configuration tool I'm aware of provides these options right for this purpose.

@farao please verify that setting `--libexecdir=/usr/libexec` fixes the isssue:

    ./waf configure --libexecdir=/usr/libexec
    ./waf build
    ./waf install

If it does, I'd say it works as designed. If not, it would be a bug.

**Comment by mwilck** [comment]
@farao,

> in my distribution (Fedora 31) for example, hamster is not packaged at all.

volunteers welcome :grin:

**Comment by GeraldJansen** [comment]
> in my distribution (Fedora 31) for example, hamster is not packaged at all.

@hedayat expressed a willingness to package hamster v3.0 for Fedora [here](https://github.com/projecthamster/hamster/issues/433#issuecomment-532599602).

**Comment by hedayat** [comment]
Yeah, hopefully I'll do that soon. Although Fedora 32 is approaching quite fast, so it might go there. But it'll be likely be available for F31 too.

**Comment by matthijskooijman** [comment]
@matthijskooijman, I don't think there's a reliable way for waf to guess these things. This is why we need options like --prefix and --libexecdir. Every serious build configuration tool I'm aware of provides these options right for this purpose.

But waf both installs the service binary somewhere, and installs the dbus file (I think?) so it could at least make them consistent with each other (which seems to have not happened).

**Comment by mwilck** [comment]
hmm, right. It does substitute `@LIBEXECDIR@` in the dbus service files though, and that substitution appears to work correctly. Maybe some other magic happened during installation on Fedora. @farao, could you provide `./waf install -vv` output?

**Comment by farao** [comment]
Hm, I just ran the uninstall and then install again and this time it chose the correct path. I also realised that I had old org.gnome.hamster.* instead of org.gnome.Hamster.* files lying around - I guess my old hamster(2) installation was simply not cleaned up properly at some point.
Sorry for making a hassle, it actually seems to work as it should.
