### ISSUE TITLE
What is the minimum Python version?

### ISSUE THREAD

**Issue by matthijskooijman** [projecthamster/hamster#582]
Anyone know what the minimum needed Python version is?

This is probably good to document somewhere (README), since it helps users to know what they need, distro packagers to specify requirements in their packages (this is why I asked) and developers to know what Python features they can and cannot use.

**Comment by ederag** [comment]
https://github.com/projecthamster/hamster/issues/388

**Comment by matthijskooijman** [comment]
Thanks for pointing that out. So, it works (or it did a year ago) in Python 3.5. Happen to know if it also works below that? I don't have an easy way to install older Python versions on this system to test, unfortunately.

**Comment by matthijskooijman** [comment]
I just noticed [some type hints in the code](https://github.com/projecthamster/hamster/blob/5a930a9c3ebdc8ed3cbfb218592deb3486f38298/src/hamster/lib/datetime.py#L106), which [are supported since 3.5](https://docs.python.org/3/library/typing.html), so that makes 3.5 the minimum Python version.
