### ISSUE TITLE
Don't use deprecated xml2po (gnome-doc-utils)

### ISSUE THREAD

**Issue by City-busz** [projecthamster/hamster#583]
Hamster currently uses xml2po to generate localized help files. xml2po is part of the [gnome-doc-utils project](https://gitlab.gnome.org/Archive/gnome-doc-utils), which is deprecated and replaced by [itstool](http://itstool.org/) / [yelp-tools](https://gitlab.gnome.org/GNOME/yelp-tools).

Please replace the xml2po usage with itstool.

**Comment by mwilck** [comment]
Is this just an enhancement request, or is our usage of xml2po causing real problems for anyone?

**Comment by City-busz** [comment]
xml2po is python2 only, and no longer maintained.

**Comment by mwilck** [comment]
On my openSUSE Tumbleweed system:

    head -n1 /usr/bin/xml2po
    #!/usr/bin/python3

So it can be made to work with py3, apparently. The fact that it's no longer maintained should be addressed of course. But I wouldn't classify this as urgent, given that xml2po is only used at build time, and has no known deficiencies wrt it's usage in the hamster build process.

Are there known security issues with xml2po?
