### ISSUE TITLE
Improve and automate testing

### ISSUE THREAD

**Issue by matthijskooijman** [projecthamster/hamster#587]
It would be good if testing the code could be automated, in the sense that all pullrequests and merges to master are automatically tested by something like Travis. This makes it easier to spot bugs.

Additionally, some style enforcement (pep8 checking e.g. @ederag mentioned planning to use black in https://github.com/projecthamster/hamster/issues/586#issuecomment-599664483) would be good, but that might require quite some investment to make the code compliant first.

Finally, the code currently uses the `unittest` framework, @ederag suggested he was planning to move to `pytest` instead. I haven't compared both frameworks, I guess pytest is more powerful or easy to work with maybe?

**Comment by mwilck** [comment]
If we want better CI, the primary todo item would be writing more tests, not switching to new framework.

**Comment by matthijskooijman** [comment]
I had a look at this today, it seems that Github actions would be an easy way to get automated checks, for example on all pull requests and the latest master branch.

Running unit tests is probably a good start.

I would also like to run some code-style (e.g. PEP-8/flake8) and linting checks. One challenge there is that the current codebase does not seem to comply with PEP-8, and running a linter over it will probably produce a lot of warnings already. Ideally, we would fix the code to be clean, and then enforce it to stay clean with CI checks after that.

Since fixing all code will be a lot of work (running `flake8` on the current master, excluding `waflib`, already produces 2089 warnings...), we might want to automate this.

For code-style, there is a relatively new tool called `black`, which automates formatting of Python code. It is intentionally not very configurable and somewhat opiniated, which I would think is a fair deal given it just results in a very consistent style (also between other projects that use black) and you can just code and run `black` afterwards to fix any inconsistencies. Black essentially applies a stricter version of PEP8 (PEP8 leaves some things open for choice, where Black makes a single choice).

I'll create a draft PR soon, so we can at least see what changes this would result in.

A downside of a lot of (automated) changes is of course that git blame results will be less usable and porting commits between branches might get more tricky...

I'm not sure if there are any automated lint-checker fixers that can do a similar thing, so linting is probably going to be harder.

**Comment by mwilck** [comment]
> A downside of a lot of (automated) changes is of course that git blame results will be less usable and porting commits between branches might get more tricky...

Indeed. I have little experience with python linting, but I'd recommend to avoid whitespace changes as much as possible.

**Comment by matthijskooijman** [comment]
I tested black reformatting, see #600. Signicant changes, including whitespace, though mostly removing or adding extra lines and rewrapping lines. From a quick glance, I see no indentation changes, so indentation was probably already consistently 4 spaces.

**Comment by matthijskooijman** [comment]
The essence of this issue is fixed with #602 (but I forgot to tag this issue in the commit, it seems), so I'm closing this. For the remaining code formatting issues, I created #606.
