### ISSUE TITLE
Release v3.0.2?

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#588]
It would be good to [release](https://github.com/projecthamster/hamster/releases) a v3.0.2 including bug fix #580.

**Comment by mwilck** [comment]
I have nothing against it. 
(FTR, the package I created for openSUSE contains this patch already).

Could you send a PR?

**Comment by GeraldJansen** [comment]
> Could you send a PR?

Sorry, but I'm not comfortable with the release process. I'd prefer to leave the release management to the maintainers.

**Comment by mwilck** [comment]
This how it works - someone creates a PR, and the maintainers will discuss and possibly merge it. You may recall that nobody can push directly to the master repo any more.

But if you'd rather wait for someone else to create the PR, fine with me.

**Comment by matthijskooijman** [comment]
Seems like creating a PR for a release is a good job for the maintainers, actually, not so much a "random" contributor would do. I haven't looked at what's involved in a release yet, probably changelog, maybe bumping a version somewhere and once it's merged, tag the resulting commit (I think we can push tags directly, though you can probably also create them through the github releases tab as well).

I can have a look later, gotta run now.

**Comment by ederag** [comment]
https://github.com/projecthamster/hamster/projects/1#card-27399663
starting after the translation stuff (that part was a stub, not up to date)

**Comment by matthijskooijman** [comment]
Probably good to include a fix for #590 as well (which is not merged yet, though).

**Comment by ederag** [comment]
Yay ! Last commit Mar 14, we are Apr 29. Let's delay some more !

**Comment by matthijskooijman** [comment]
> Yay ! Last commit Mar 14, we are Apr 29. Let's delay some more ! smile

I'm not entirely sure what you mean here. I suspect you're being cynical? If you have alternative proposals, please state them plainly with arguments, so we can have constructive discussions.

**Comment by ederag** [comment]
https://github.com/projecthamster/hamster/pull/580#issuecomment-600045167
https://github.com/projecthamster/hamster/issues/588#issuecomment-600225334

**Comment by matthijskooijman** [comment]
Not much more plain, but well. I can probably guess what you mean.

My original thought was that #590 is a very similar problem (with offsets in dates), so it would be good to include that. However, it seems the fix is a little bit more involved, so maybe releasing what we have now might indeed be better than trying to fix #590 first (e.g. rather than spending time fixing that, better spend some time figuring out the release process first).

I'll have a go at preparing a release, probably though a PR, using the checklist @ederag linked.

**Comment by GeraldJansen** [comment]
Thanks and congratulations on the first release made by the new maintainers.
