### ISSUE TITLE
Activity list jumps to top after some short time

### ISSUE THREAD

**Issue by dfn-certling** [projecthamster/hamster#594]
If I list for example all activities for a month, the list is obviously larger than one screen. When I scroll down this list some way, the list jumps back to the top on its own after some time of waiting. Sometimes its 5 seconds, sometimes a minute.

I would expect the list to stay at the scrolled to position.

This is with hamster 3.0.1 on SUSE Tumbleweed using lightdm.

Anything else I can provide to help debug this?

**Comment by markferry** [comment]
Seems to be pretty much once a minute.

Comments in the output of strace indicate when I observed the UI jump back to the top:

[hamster-issue-594-strace.txt](https://github.com/projecthamster/hamster/files/4875051/hamster-issue-594-strace.txt)

```shell
$ uname -a
Linux canard 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64 GNU/Linux
```

```shell
$ pacman -v -Ss hamster
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : hamster
community/hamster-time-tracker 3.0.1-1 [installed]
    Time tracking application that helps you to keep track on how much time you have spent during the day on
    activities you choose to track
```

Arch linux on Dell XPS13 9370.

**Comment by mwilck** [comment]
Thanks for the trace. Could you confirm (via `ls /proc/$PID/fd`) what  fd 3 is? I suppose it's the X server socket but I'd like to be more certain.

**Comment by mwilck** [comment]
Do you have the shell extension running? It seems that hamster receives a "GetFactsJSON" dbus method call just before this happens.

**Comment by mwilck** [comment]
> Do you have the shell extension running? It seems that hamster receives a "GetFactsJSON" dbus method call just before this happens.

Nonsense, the Shell extension doesn't use that method call. It's probably rather hamster-cli itself that sends it.

**Comment by mwilck** [comment]
> Thanks for the trace. Could you confirm (via `ls /proc/$PID/fd`) what fd 3 is? I suppose it's the X server socket but I'd like to be more certain.

Forget it, not necessary any more.

**Comment by mwilck** [comment]
Please check out #623.

**Comment by dfn-certling** [comment]
Yes, that seems to solve it. I'll keep using that version for the following days to see whether something else breaks.

I agree with your concern that now switching to the previous month it might be strange that the list doesn't jump to the top - but maybe that's just about getting used to. I certainly prefer no jumps to regular jumps =).

**Comment by dfn-certling** [comment]
No problems with using this version for my use cases.
