### ISSUE TITLE
Hamster applet fails after fresh install (Ubuntu 18.04, Cinnamon 3.6.7)

### ISSUE THREAD

**Issue by mauntrelio** [projecthamster/hamster#604]
I have succesfully used Hamster applet until now with Cinnamon 3.2.7
After fresh install of the applet in Cinnamon 3.6.7 the applet only shows the icon (no tracking, no dialogs). These errors appear in the .xsession-errors log:

Cjs-Message: 12:19:09.240: JS LOG: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Hamster was not provided by any .service files

(cinnamon:4351): Cjs-WARNING **: 12:21:01.928: JS ERROR: Exception in callback for signal: activate: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Hamster.WindowServer was not provided by any .service files
_proxyInvoker@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:94:16
_makeProxyMethod/<@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:124:16
HamsterApplet.prototype._onShowHamsterActivate@/home/maurizio/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/applet.js:552:9
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
PopupBaseMenuItem.prototype.activate@/usr/share/cinnamon/js/ui/popupMenu.js:178:9
PopupBaseMenuItem.prototype._onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:151:9

Any help would be highly appreciated

**Comment by mwilck** [comment]
Hm, "hamster applet" has been dead for years ... IIRC it was the predecessor of the GNOME extension, but I'm not even exactly certain about that any more.

I have no knowledge about Cinnamon. Can it run GNOME extensions? If yes, you may want to try one of our newer releases of the extension (here on Github). 

> org.gnome.Hamster.WindowServer was not provided by any .service files

This sounds as if hamster itself isn't cleanly installed. What distro is this? What version of hamster?

**Comment by mauntrelio** [comment]
Thank you for the quick reply.

I am using Ubuntu 18.04, with official Cinnamon packages from Ubuntu (Cinnamon v. 3.6.7)
The applet is installed via "Add applet to the panel > Download".
The information link on the applet installation window redirects to this web page:
https://cinnamon-spices.linuxmint.com/applets/view/140

If I look into the files downloaded into `~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com` I found a file `metadata.json` with the following content:

```json
{
    "external-configuration-app": "prefs.js", 
    "uuid": "hamster@projecthamster.wordpress.com", 
    "url": "https://github.com/projecthamster/cinnamon-applet", 
    "dangerous": false, 
    "description": "Cinnamon applet for project hamster - the GNOME time tracker", 
    "original-authors": [
        "toms.baugis@gmail.com", 
        "jerome@oufella.com", 
        "jonbrett.dev@gmail.com"
    ], 
    "extension-id": "project-hamster", 
    "version": 0.2, 
    "last-edited": 1571980935, 
    "name": "Project Hamster Applet"
}
```
I am not sure about Gnome extensions.
So far I have been using the Hamster applet in Debian and Ubuntu 16 with cinnamon version 3.2.7 and everything was working fine (with the same installation procedure as described), however I see that the version of the applet downloaded is still the same, so something broke in Cinnamon 3.6 (which is not even the latest).
I will try to understand if I can install the extension as you suggest.

**Comment by mwilck** [comment]
Unfortunately, https://github.com/projecthamster/cinnamon-applet has been marked deprecated fore more than 3 years. I wasn't aware anyone was still using it. Sorry to say it, but if you want to revive it, I guess you have to sit down and code yourself.

**Comment by mauntrelio** [comment]
Yes, I had a look... and unfortunately I think you are right...
Actually I think it should be removed by the list of available applets for Cinnamon (however I don't know how that works in detail).
I am currently looking for other time trackers. So far I cannot find anything with the lovely simplicity and the plain wonderful approach hamster has (and that could work with Cinnamon).
I do not exclude the solution you propose (coding myself)... I am just afraid this will take a lot of time just to understand the background of the Cinnamon desktop environment.
In any case, thanks a lot for your support.

**Comment by mwilck** [comment]
Thanks for your warm words about hamster. The github home page of the cinnamon applet says that it "is now maintained by the Mint Linux team", and links to [cinnamon-applet #30](https://github.com/projecthamster/cinnamon-applet/issues/30), which is also 3y old. Some more recent work has been going on in https://github.com/linuxmint/cinnamon-spices-applets/tree/master/hamster%40projecthamster.wordpress.com, it seems.

**Comment by mauntrelio** [comment]
**I made it work!! Hurra!!**

Ok, just for the records (and might be useful for somebody else), I manged to make it work again in Ubuntu 18.04, Cinnamon 3.6.7) (BTW, I am an old guy, I like old software...).

- Retrieved old Deb package python-wnck 2.32 (which was removed from Ubuntu 18)
- Retrieved old Deb package Hamster applet 2.91.3 (removed as well because of unmet dependencies caused probably by the aforementioned removal)
- Manually installed other Hamster applet package dependencies (namely python-gnome2, python-gconf)
- Manually installed the retrieved packages
- Re-installed the applet from the official Cinnamon applet installer
- It works!!! (So far, so good, no conflicts with other stuff)
