### ISSUE TITLE
Stop button icon is not intuitive

### ISSUE THREAD

**Issue by u451f** [projecthamster/hamster#635]
tags: enhancement, UX

(On a sidenote: I'm so glad I only report UX and enhancement feature requests, not bugs! You did such a great job on this software!)

It took me several minutes (!) to find how the stop an activity. This is because the icon used on the stop button (a circle around a dot) is not clearly distinguishable as a symbol that my brain connects to stopping something.

Interestingly, our culture does not seem to have good iconography for saying stop :) There is a hand palm, or a square (associated with a triangle pointing right for play). Even video players (like the ones on Youtube) nowadays only have pause signs, not stop signs.

Still, to me, a black square would work better than the current icon.

**Comment by fantasai** [comment]
I think it's supposed to be a stop sign. If it was a bright red octagon, that might be clearer. :) But I agree the current icon isn't very obvious.

**Comment by DirkHoffmann** [comment]
The stop button is now a cross.
Personally I would also prefer the stop button as older people are used to know it from magnetic tape machines. But it is a convention as many others. I propose closure of this issue.
