### ISSUE TITLE
Issue of popup position of RangePick on Debian 10 with wayland

### ISSUE THREAD

**Issue by taniwallach** [projecthamster/hamster#645]
Originally discussed in: https://github.com/projecthamster/hamster/issues/639.

On Debian 10 with wayland: the popup always opens in the top left of the screen, and not placed over the hamster window (offset down and right a bit).

---

Le mercredi 18 novembre 2020, Nathan Wallach a écrit :
> It is possible that the data below hints that these issues are related to one of:
>   - `xorg` (was in use on the machine where there was an issue) vs `wayland` (in use on the machine where things worked) **seems more likely**

I confirm that a combination of wayland + not very recent GTK version
creates this issue where some popups windows are misplaced. I got the same
problem in another application (tryton).

Cheers,
-- 
Raphaël Hertzog

_Originally posted by @rhertzog in https://github.com/projecthamster/hamster/issues/639#issuecomment-729788375_

---
Some issues of popup positioning with wayland were fixed by https://github.com/projecthamster/hamster/pull/527. Perhaps the same fix is needed here.

_Originally posted by @GeraldJansen in https://github.com/projecthamster/hamster/issues/639#issuecomment-729796719_

**Comment by matthijskooijman** [comment]
I looked a bit at the PR @GeraldJansen posted, which seem like good changes to apply here as well. However, while looking around the GTK docs, I also noticed that there is a ["GtkPopOver" object](https://valadoc.org/gtk+-3.0/Gtk.Popover.html), which might even be more suitable for this usecase than the popup GtkWindow we are using now. In particular, this PopOver already automatically handles grabbing the focus and hiding when you click beside the window, which is exactly what we need here. This means that:
 - The custom and slightly hacky `on_focus_out` handling can just be removed
 - When clicking beside the window to close it, that click is actually not propagated to whatever is underneath (which allows removing the hacky part of `on_focus_out`), and is probably more what users expect.
 - The issue in #639 is is probably fixed as a side effect of the above.
 - The placement issue described here is probably fixed (needs testing)
 - Pressing "ESC" now also closes the popover.

The popover does look slightly different, it uses a pointy triangle:

![image](https://user-images.githubusercontent.com/194491/99565694-3e497200-29cc-11eb-910f-e128ad6a4388.png)

I did find a small downside: It seems the popover is constrained to the containing window, so if you make that small, it starts to look bad:

![image](https://user-images.githubusercontent.com/194491/99565784-5caf6d80-29cc-11eb-87a5-171c9260328e.png)

But that does not seem like a big problem to me.

@taniwallach, Could you check if https://github.com/projecthamster/hamster/commit/2ce19fc653263315903fd1712562fc6bbd17c44f actually fixes the problem with placement you are seeing? If you install the changes into the system-wide version manually, you probably need to update `/usr/share/hamster/date_range.ui`.

**Comment by taniwallach** [comment]
A branch created from commit https://github.com/projecthamster/hamster/commit/2ce19fc653263315903fd1712562fc6bbd17c44f seems to work fine on both machines:
  - the one with wayland which had the placement issue, and 
  - the one which had the missing popup issue discussed in https://github.com/projecthamster/hamster/issues/639
The popup opens/closes and selection behaves as expected, with no placement issue on either machine.

Procedure used to install/test:
```
git fetch origin
git checkout 2ce19fc653263315903fd1712562fc6bbd17c44f
git checkout -b GtkPopOver-try01
./waf configure build
( umask 0022 && sudo ./waf install; )
pkill -f hamster-service ; /usr/bin/hamster
```
and the experiment with the popup and how it behaves.
