### ISSUE TITLE
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.3 was not provided by any .service files

### ISSUE THREAD

**Issue by klugjohannes** [projecthamster/hamster#68]
I installed hamster from source and the shell extension from extensions.gnome.org as documented. Entering an activity in the shell extension has no effect. Trying to run hamster from cli results in the error message given in the title.

Full stacktrace is

<pre>
WARNING:root:Could not import wnck - workspace tracking will be disabled
ERROR:dbus.proxies:Introspect error on :1.250:/org/gnome/Hamster: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
Traceback (most recent call last):
  File "/usr/bin/hamster", line 374, in <module>
    hamster_client.today()
  File "/usr/bin/hamster", line 136, in today
    app = today.DailyView()
  File "/usr/lib/python2.7/site-packages/hamster/today.py", line 90, in __init__
    self.create_hamster_window()
  File "/usr/lib/python2.7/site-packages/hamster/today.py", line 148, in create_hamster_window
    self.new_name = widgets.ActivityEntry()
  File "/usr/lib/python2.7/site-packages/hamster/widgets/activityentry.py", line 103, in __init__
    self.populate_suggestions()
  File "/usr/lib/python2.7/site-packages/hamster/widgets/activityentry.py", line 234, in populate_suggestions
    self.activities = runtime.storage.get_activities(fact.activity)
  File "/usr/lib/python2.7/site-packages/hamster/client.py", line 137, in get_activities
    return self._to_dict(('name', 'category'), self.conn.GetActivities(search))
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 68, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 140, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 630, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.250 was not provided by any .service files
</pre>

`tail /var/log/messages`

<pre>
Jan 16 11:52:08 telemachus abrt: detected unhandled Python exception in '/usr/lib/hamster-time-tracker/hamster-service'
Jan 16 11:52:08 telemachus abrtd: New client connected
Jan 16 11:52:08 telemachus abrtd: Directory 'pyhook-2013-01-16-11:52:08-3319' creation detected
Jan 16 11:52:08 telemachus abrt-server[3320]: Saved problem directory of pid 3319 to '/var/spool/abrt/pyhook-2013-01-16-11:52:08-3319'
Jan 16 11:52:08 telemachus abrtd: Executable '/usr/lib/hamster-time-tracker/hamster-service' doesn't belong to any package
Jan 16 11:52:08 telemachus abrtd: 'post-create' on '/var/spool/abrt/pyhook-2013-01-16-11:52:08-3319' exited with 1
Jan 16 11:52:08 telemachus abrtd: Corrupted or bad directory '/var/spool/abrt/pyhook-2013-01-16-11:52:08-3319', deleting
Jan 16 11:52:08 telemachus abrt: detected unhandled Python exception in '/usr/lib/hamster-time-tracker/hamster-service'
Jan 16 11:52:08 telemachus abrtd: New client connected
Jan 16 11:52:08 telemachus abrt-server[3325]: Not saving repeating crash in '/usr/lib/hamster-time-tracker/hamster-service'
</pre>

System is Fedora 17, running Gnome-Shell 3.4.1

**Comment by sixtyfive** [comment]
Same error here at the end of the stacktrace, but nothing about wnck:

```
$ hamster 
Traceback (most recent call last):
  File "/usr/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.2819 was not provided by any .service files
```

**Comment by toupeira** [comment]
@sixtyfive what version are you using and how did you install it?

**Comment by sixtyfive** [comment]
Hi @toupeira! I've compiled Git as of 9 hours ago. The nightly from the PPA (which, like I said, installs without trouble under Debian Jessie) shows the same message by the way. The git version I installed through `sudo su ; ./waf configure build --prefix=/usr ; ./waf install`, which should be close enough to the instructions given in `README.md`, correct?

**Comment by toupeira** [comment]
@sixtyfive not sure if passing both `configure` and `build` does the right thing, can you try as follows (as root, though it's only required for the `install` step):

```sh
./waf clean
./waf configure --prefix=/usr
./waf install
```

Make sure each command exits successfully without errors, and then check if these paths exist:
- `/usr/share/dbus-1/services/org.gnome.hamster.service`
- `/usr/share/dbus-1/services/org.gnome.hamster.Windows.service`

You can also try running the services directly using `/usr/lib/hamster-time-tracker/hamster-service` or `/usr/lib/hamster-time-tracker/hamster-windows-service`, maybe you'll get a more helpful error message this way.

**Comment by sixtyfive** [comment]
Hi! So all three commands came back successfully. But I don't have either one of the two files you mention. Instead I have:

* `/usr/share/dbus-1/services/org.gnome.hamster.service.in`
* `/usr/share/dbus-1/services/org.gnome.hamster.Windows.service.in`

Starting both services as mentioned and then starting `hamster` works fine now! No error messages, just some warnings about deprecated Gtk things.

The window looks like this, which I'm not sure of if everything is the way it's supposed to be? http://pasteboard.co/19iaImsM.png – in any case, entering new tasks works just fine, so I'm a happy beaver (or rather, a hamster?) now. Thank you! :)

**Comment by tbaugis** [comment]
@sixtyfive i believe this bug is dupe of #254 - please pull from git and install hamster again and see if the problem goes away

**Comment by sixtyfive** [comment]
@tbaugis: See my comment from an hour ago - using @toupeira's instructions it works! Thank you!

**Comment by toupeira** [comment]
@sixtyfive glad you got it working, though I'm still confused why you don't get the correct service files. In the `./waf install` output you should see these lines:

```
* installing build/default/org.gnome.hamster.service as /usr/share/dbus-1/services/org.gnome.hamster.service
* installing build/default/org.gnome.hamster.Windows.service as /usr/share/dbus-1/services/org.gnome.hamster.Windows.service
```

**Comment by sixtyfive** [comment]
Okay, so apparently I only needed to run it a second time. The `.in` files vanished now and got replaced by the proper ones. Thank you again!

**Comment by toupeira** [comment]
Hmm that's very strange, but glad you got it working!
