### ISSUE TITLE
Monthly view scrolls to top automatically

### ISSUE THREAD

**Issue by szebenyib** [projecthamster/hamster#683]
Steps to reproduce:
- Switch to month view
- Scroll down to see the bottom part of the month
- Wait
- The screen will jump to the top

Expected behaviour:
- Just stay where I scroll

The above automation or bug makes it hard to check and retrieve data from hamster due to the content always skipping to the beginning of the month.

**Comment by GeraldJansen** [comment]
Probably fixed by #648.

**Comment by szebenyib** [comment]
Just checked and my version number is 3.0.2-2 (arch). Sorry, forgot to add. So with that release being in 2020 May, and that PR 2020 december the given PR might be a fix for this. I will close it for now and wait for the next release. Thank you.
