### ISSUE TITLE
Traceback 'Fact' object has no attribute 'name'

### ISSUE THREAD

**Issue by snai** [projecthamster/hamster#72]
I am using the 'awesome Windowmanager'.

When I configure  the Workspace Tracking properties, in order to stop / start tracking on defined workspace, I keep getting this traceback on console:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/hamster/today.py", line 422, in on_workspace_changed
    fact = Fact(activity.name,
AttributeError: 'Fact' object has no attribute 'name'
```

Furthermore, nothing happens when changing the workspace (the current Activity is not stopped, nor a new one is created when switching to the predefined workspace)

Let me know, if you need more information, or if this is unrelated, due to unsupported windowmanager.

**Comment by indradhanush** [comment]
I am seeing the same error. Can this be reopened please?
Here's the full traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hamster/today.py", line 416, in on_workspace_changed
    self.last_activity.name.lower() == activity.name.lower() and \
AttributeError: 'Fact' object has no attribute 'name'
```

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by ederag** [comment]
Closing, since this issue is thought to be solved in the development version.
(the meaning of the hamster-applet label has been [changed](https://github.com/projecthamster/hamster/issues/312#issuecomment-521266921))
Thanks for contributing to hamster improvement !
