### ISSUE TITLE
Application no longer running: i18n.setup_i18n() error

### ISSUE THREAD

**Issue by in0ni** [projecthamster/hamster#721]
Hello, after a recent update of packages I am unable to run the application. Simply commenting out line 25 of i18n.py fixes the issue (surely not the right fix, but works for me)

```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 415, in <module>
    i18n.setup_i18n()
  File "/usr/lib/python3.11/site-packages/hamster/lib/i18n.py", line 24, in setup_i18n
    module.bind_textdomain_codeset('hamster','utf8')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gettext' has no attribute 'bind_textdomain_codeset'
```

**Comment by GeraldJansen** [comment]
This issue is already resolved by PR #715 (merged).

**Comment by in0ni** [comment]
That's great to know... to bad this PR did not make it to the latest release (or perhaps the arch package should be marked out of date).

**Comment by sr-verde** [comment]
The real problem is: There is _no_ latest release. But this issue should be closed.

**Comment by matthijskooijman** [comment]
Agreed
