### ISSUE TITLE
Use at least 128x128 icons

### ISSUE THREAD

**Issue by bbhtt** [projecthamster/hamster#724]
Flathub appstream check needs a 128x128 icon at least.

Remote icon is not supported so on the new flathub.org frontend Hamster doesn't have any icon.

I'll upscale the current 48x48 icon as a workaround, but it'll look very blurry.

**Comment by A6GibKm** [comment]
This report is wrong, the app has a scalable svg icon, thats all it needs.

**Comment by bbhtt** [comment]
Closing as per above comment, I didn't notice the svg icon.
