### ISSUE TITLE
Keyboard shortcut to unselect current activity

### ISSUE THREAD

**Issue by mach-o** [projecthamster/hamster#735]
I would like to be able to unselect the current activity using the keyboard. I believe you currently must do this by clicking on the activity with the mouse cursor.

My use case is that I often want to Add an activity (Ctrl-+) but don't want the fields in the new activity to be pre-filled based on the currently selected activity. I just want them to be blank. In this case I have to use the mouse cursor to find and then deselect the current activity, and then use the shortcut key afterwards.

I might recommend the tab key for this, or failing that the space bar, which don't seem to be taken. "Enter" is already used to open the selected activity, "Esc" quits the program.

**Comment by GeraldJansen** [comment]
Please note that you can create a new issue from scratch using Ctl+N. Does that not suffice?

**Comment by mach-o** [comment]
That works, thank you!
