### ISSUE TITLE
remove dependency on deprecated distutils package

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/hamster#759]
As of Python 3.10 the distutils package has been deprecated and it will be removed from Python 3.12.

Hamster has a minor dependency on distutils in src/hamster/client.py. I will make a PR shortly.

The dependency on python3-distutils should be replaced by python3-packaging.

**Comment by matthijskooijman** [comment]
Are you sure? I think this was already fixed by https://github.com/projecthamster/hamster/pull/749/commits/f14e4276d11c5d69fb6da844735cffc7a718f1f1 ?

**Comment by GeraldJansen** [comment]
Oops, sorry for the noise. I thought my fork was up-to-date but alas, no.
