### ISSUE TITLE
Report total incorrect

### ISSUE THREAD

**Issue by ajrouvoet** [projecthamster/hamster#76]
It's an early morning for me and I hope I haven't overlooked something incredibly stupid, but I think the report totals are incorrect for me.

Every month I export my monthly report to a tsv file and sum the whole lot for my employer. The grand totals always matched up, but since the latest update they don't anymore.
### Summed minutes in xls

3717 minutes = 61.95 hours
### Total time in hamster

62.4 hours

Any help is appreciated.

**Comment by ederag** [comment]
This should be fixed by PR #429, thanks @GeraldJansen !
