### ISSUE TITLE
Gdm not displaying anything after coming back from lockscreen

### ISSUE THREAD

**Issue by faebser** [projecthamster/hamster#84]
I'm using Ubuntun 12.10 and GNOME Shell 3.6.2. When enabling hamster and shell-extension (both freshly checked out from github) I experience a rather nasty problem.
After locking my machine the lockscreen shows up. I input my password but then the view won't change back to my desktop but the background of the lockscreen stays on top. I then have to restart gdm to access my desktop.

**Comment by ederag** [comment]
Thanks for the report.
Cannot reproduce with [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1).
Is it fixed ?
