### ISSUE TITLE
CLI `export` does not populate javascript variable `dateFacts`

### ISSUE THREAD

**Issue by MaciekChudek** [projecthamster/hamster#96]
Exporting HTML from the command line does not correctly populate the javascript `dateFacts` variable in the resulting webpage. This seems to be because the start_date and end_date variables in the HTMLWriter class have a time string attached for some reason I couldn't easily spot.

I circumvented this by changing lines 291 and 292 in reports.py from

```
        date = self.start_date
        while date <= self.end_date:
```

to 

```
        date = self.start_date.date()
        while date <= self.end_date.date():
```

which seemed to do the trick. But I didn't go deep enough to find out whether this hack would break things elsewhere.

**Comment by ederag** [comment]
Thanks for your contribution.
Should be fixed since PR #375.
